"use client";
import { BrandLogo } from "@/components/brand-logo";

import Link from "@/components/platform-experience/link";
import { useSearchParams } from "next/navigation";
import { useRouter } from "@/components/platform-experience/link";
import { useEffect, useRef, useState, type ReactNode } from "react";
import type { Membership, Theme } from "@/modules/ux-prototype/model";
import { Icon, lessonHref, lessonVisuals, modules, studentHref, studentNav } from "./reference";
import { useStudentLearning } from "./use-student-learning";
import { GuidanceContent } from "./guidance";
import "./student.css";

const stages = [
  { n: 1, title: "把一首歌完整彈完", copy: "先把最基本的動作連起來，讓一首歌從頭到尾走完。" },
  { n: 2, title: "讓伴奏不再只有一種", copy: "從穩定的拍子開始，練習停音、留白，再把節奏放進一首歌裡。" },
  { n: 3, title: "開始知道自己在彈什麼", copy: "慢慢理解和弦與音樂之間的關係，讓選擇不再只是憑感覺。" },
];
const practiceItems = [["先用空弦找回拍子", "先不急著換和弦，右手穩定往前。", "2 分鐘"], ["把切音動作慢慢拆開", "先讓聲音停下，再接回下一拍。", "3 分鐘"], ["跟伴奏把一小段彈完", "今天先練一小段就好。", "5 分鐘"]];
const themeNames = { light: "白色", dark: "黑色", system: "系統預設" };

export function StudentPage({ segments }: { segments: string[] }) {
  const query = useSearchParams();
  const learning = useStudentLearning(query.get("package") || undefined);
  const { state, student, dispatch } = learning;
  const router = useRouter();
  const route = segments.includes("guidance") ? "guidance" : segments[0] || "today";
  const isGuidanceSubmit = segments.includes("units");
  const [collapsed, setCollapsed] = useState(false);
  const [effectiveTheme, setEffectiveTheme] = useState<"dark" | "light">("dark");
  const [courseTab, setCourseTab] = useState("ongoing");
  const [privateTab, setPrivateTab] = useState("next");
  const requestedStage = Number(query.get("stage"));
  const viewStage = requestedStage >= 1 && requestedStage <= 3 ? requestedStage : learning.fresh ? 1 : 2;
  const setViewStage = (stage: number) => router.push(`${studentHref("map")}?stage=${stage}`);
  const { timeZone: zone, setTimeZone: setZone } = learning;
  const [modal, setModal] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  const [search, setSearch] = useState("");
  const [slot, setSlot] = useState("");
  const [confirmBooking, setConfirmBooking] = useState(false);
  const privateChecks = student.privatePracticed || [];
  const dialog = useRef<HTMLDialogElement>(null);
  const menu = useRef<HTMLDialogElement>(null);
  const rail = useRef<HTMLDivElement>(null);
  const currentLesson = lessonVisuals.find(item => item.id === learning.currentLessonId) || lessonVisuals[2];
  const currentIndex = lessonVisuals.indexOf(currentLesson);
  const hasPrivate = !!learning.pack;
  const d = dateInfo(learning.nextBooking?.start, zone);
  const teacherName = learning.teacher?.published?.name || "The One 老師";
  const privateFeedback = learning.feedback.find(reply => state.submissions.some(item => item.id === reply.submissionId && item.kind === "private" && item.teacherId === learning.pack?.teacherId));
  const fixedSlot = learning.nextBooking || state.availability.find(item => item.teacherId === learning.pack?.teacherId && item.mode === "fixed" && item.priorityStudentId === student.id);
  const fixedTime = fixedSlot ? dateInfo(fixedSlot.start, zone) : null;

  useEffect(() => {
    const scheme = window.matchMedia("(prefers-color-scheme: dark)");
    const apply = () => setEffectiveTheme(learning.theme === "system" ? scheme.matches ? "dark" : "light" : learning.theme);
    apply(); scheme.addEventListener("change", apply); return () => scheme.removeEventListener("change", apply);
  }, [learning.theme]);
  useEffect(() => { if (!modal) return; dialog.current?.showModal(); dialog.current?.querySelector<HTMLElement>(modal === "search" ? "input" : "button")?.focus(); }, [modal]);
  useEffect(() => { if (!notice) return; const id = setTimeout(() => setNotice(""), 5200); return () => clearTimeout(id); }, [notice]);

  const go = (path: string) => { dialog.current?.close(); menu.current?.close(); router.push(studentHref(path)); };
  const openModal = (id: string) => { setModal(id); if (id === "booking") { setSlot(""); setConfirmBooking(false); } };
  const closeModal = () => { dialog.current?.close(); setModal(null); };
  const join = () => { const result = dispatch({ type: "joinCourse", studentId: student.id, courseId: "c1" }); if (result.ok) { closeModal(); go("courses"); setNotice("已明確加入示意課程，個人進度從 0 開始。沒有購買、升級或授予額外存取權。"); } else setNotice(result.error || "無法加入"); };
  const continueLink = learning.fresh ? studentHref("map") : lessonHref(currentLesson.id);

  function pageHeader(eyebrow: string, title: string, subtitle: string, extra?: ReactNode) {
    return <header className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><div className="header-tools">{extra}<button className="icon-button" onClick={() => openModal("search")} aria-label="搜尋課節"><Icon name="search" /></button><Link className="icon-button" href={studentHref("settings")} aria-label="外觀設定"><Icon name={effectiveTheme === "dark" ? "moon" : "sun"} /></Link></div></header>;
  }
  const progressLine = () => <div className="progress-line"><div className="track"><span style={{ width: `${learning.done.length / 6 * 100}%` }} /></div><span>{learning.fresh ? "尚未開始" : `${learning.done.length} / 6 課 · 自報完成`}</span></div>;
  function continueCard() {
    return <div className="continue-card"><div className="eyebrow">{learning.enrolled ? <><span className="state-pulse" style={{ background: "#ffdc35" }} />{learning.fresh ? "已加入的系統課程" : "繼續你正在走的路"}</> : "你的第一條學習路線"}</div><h2>The One<span>Guitar Roadmap 2.0</span></h2>{learning.enrolled ? <><div className="current-line">{learning.fresh ? "Stage 1 · 從第一步開始" : `Stage 2 · ${modules[currentLesson.module]}`}</div><div className="current-lesson">{learning.fresh ? "準備開始你的第一堂課" : `${String(currentIndex + 1).padStart(2, "0")}｜${currentLesson.title}`}</div>{progressLine()}<div className="continue-actions"><Link className="btn primary" href={continueLink}><Icon name="play" />{learning.fresh ? "從第一步開始" : "繼續學習"}</Link><Link className="text-button" href={studentHref("map")}>查看我的學習地圖<Icon name="arrowUpRight" /></Link></div></> : <><div className="current-line">從「想彈好」，到知道下一步怎麼練。</div><p style={{ fontSize: 12, color: "#c6c1af", marginTop: 11, maxWidth: 340 }}>先認識這套課程。加入之後，這裡才會出現你的階段與學習進度。</p><div className="continue-actions"><button className="btn primary" onClick={() => openModal("intro")}>認識吉他學習地圖<Icon name="arrow" /></button></div></>}</div>;
  }
  function practicePanel() {
    if (!learning.enrolled || learning.fresh) return <section className="today-practice"><div className="head-row"><h2>今天，先找到你的起點</h2><p className="subtitle">不需要一次決定整段旅程。</p></div><p className="subtitle" style={{ marginTop: 15, lineHeight: 2 }}>看看課程在教什麼，選一段示範內容感受上課方式。{learning.enrolled ? "你已加入，接下來從第一個階段開始。" : "加入課程後，這裡再接上你當前課節的練習。"}</p><div className="practice-end"><button className="text-button" onClick={() => openModal("intro")}>認識學習路線<Icon name="arrow" /></button></div></section>;
    return <section className="today-practice"><div className="head-row row between"><div><h2>今天先練這三件事</h2><p className="subtitle">接著目前這一課，留 10 分鐘給自己。</p></div></div>{practiceItems.map(([title, copy, duration], i) => <label className="practice-row" key={title}><input type="checkbox" checked={learning.practiced.includes(`practice-${i}`)} onChange={() => learning.togglePractice(`practice-${i}`)} aria-label={title} /><span className="practice-copy">{title}<small>{copy}</small></span><span className="duration">{duration}</span></label>)}<div className="practice-end"><span className="practice-count">今天已勾選 {learning.practiced.filter(id => id.startsWith("practice-")).length} / 3 · 本機示意</span><Link className="text-button" href={studentHref("practice")}>打開練習<Icon name="right" /></Link></div></section>;
  }
  function upcomingStrip() {
    if (!hasPrivate) return null;
    return <div className="next-strip"><Icon name="calendar" className="strip-icon" /><div className="grow"><div className="strip-title">{learning.nextBooking ? `下一堂私人課 · ${d.date}　${d.time}` : learning.credit.available > 0 ? "你有可用的私人課堂數，還沒排下一堂" : "這期私人課已使用完畢"}</div><div className="strip-sub">{teacherName}（示意） · {learning.pack?.mode === "fixed" ? "固定制" : "預約制"} · {zoneLabel(zone)}</div></div>{learning.nextBooking && <div className="strip-feedback">老師的練習提醒：先把速度放慢，讓切音後的下一拍更穩。</div>}<Link className="text-button" href={studentHref("private")}>{learning.nextBooking ? "查看這堂課" : "前往私人課"}<Icon name="arrow" /></Link></div>;
  }
  function lessonCard(i: number) { const l = lessonVisuals[i]; return <Link className="content-card" key={l.id} href={lessonHref(l.id)} aria-label={`開啟課節示意：${l.title}`}><span className={`cover ${l.style}`}><span className="tag">STAGE 2 / LESSON {String(i + 1).padStart(2, "0")}</span><span className="cover-title">{l.hero[0]}<br />{l.hero[1]}</span><span className="cover-bottom">THE ONE · GUITAR ROADMAP</span><span className="cover-number" aria-hidden="true">{String(i + 1).padStart(2, "0")}</span><span className="cover-play"><Icon name="playOutline" /></span></span><span className="content-title">{l.title}</span><span className="content-meta">吉他學習地圖 · {modules[l.module]}</span><span className="content-sub"><Icon name={learning.done.includes(l.id) ? "check" : "playOutline"} />{learning.enrolled && !learning.fresh ? currentLesson.id === l.id ? "目前這一課" : learning.done.includes(l.id) ? "可回頭複習" : "建議接著練" : "課節預覽 · 不代表已加入"}</span></Link>; }
  function rails() { return <><section className="section"><div className="section-head"><div><h2>{learning.enrolled && !learning.fresh ? "接著練這些" : "先看看，你會怎麼學"}</h2><p className="subtitle">來自同一套吉他學習地圖，不是另外販售的課程。</p></div><div className="section-actions">{[-1, 1].map(direction => <button className="icon-button" key={direction} aria-label={direction === 1 ? "往後瀏覽課節" : "往前瀏覽課節"} onClick={() => rail.current?.scrollBy({ left: direction * Math.max(250, rail.current.clientWidth * .75), behavior: "smooth" })}><Icon name={direction === 1 ? "right" : "left"} /></button>)}</div></div><div className="rail-list" ref={rail}>{[2, 3, 4, 5, 0, 1].map(lessonCard)}</div></section><section className="section"><div className="section-head"><div><h2>換一種方式，練這一課</h2><p className="subtitle">教學、練習與伴奏，仍然在同一堂課裡。</p></div></div><div className="resource-row">{[["practice", "慢速拆解", "把動作拆開，先求穩。", "practice"], ["file", "節奏變化", "同一個和弦，換一種表情。", "apply"], ["audio", "跟伴奏彈", "把剛才的練習放進音樂。", "jam"]].map(([icon, title, copy, activity]) => <Link href={lessonHref(currentLesson.id, activity)} className="resource-tile" key={title}><Icon name={icon} /><span><strong>{title}</strong><small>{copy}</small></span><Icon name="right" className="arrow" /></Link>)}</div></section></>; }
  function journey() { return <><div className="journey" aria-label="這套課程的階段旅程，代表性示意">{stages.map(s => { const st = learning.fresh ? s.n === 1 ? "current" : "upcoming" : s.n === 1 ? "done" : s.n === 2 ? "current" : "upcoming"; return <button className={`stage-step ${st}${viewStage === s.n ? " selected" : ""}`} key={s.n} aria-pressed={viewStage === s.n} onClick={() => { setViewStage(s.n); }}><span className="stage-top"><span className="stage-dot">{st === "done" ? <Icon name="check" /> : s.n}</span><small>STAGE {s.n}</small></span><strong>{s.title}</strong><span className="stage-status">{st === "done" ? "自報完成 · 可回看" : st === "current" ? learning.fresh ? "目前階段 · 尚未開始" : `目前階段 · ${learning.done.length} / 6 課` : "尚未開始 · 可先了解"}</span></button>; })}<div className="stage-step future"><span className="stage-top"><span className="stage-dot">…</span></span><strong>後續旅程</strong><span className="stage-status">依正式課綱展開</span></div></div><p className="journey-caption">只展示代表性階段，不固定正式階段總數。未開始不等於鎖定；自報完成不等於老師驗證或取得證書。</p></>; }
  function emptyCourse() { return <div className="empty"><Icon name="courses" /><h2>把第一套學習路線，放進這裡。</h2><p>你還沒有加入系統課程。推薦只是幫你找到方向，不會自動變成「我的課程」，也不會先替你產生學習進度。</p><button className="btn primary" onClick={() => openModal("intro")}>認識吉他學習地圖<Icon name="arrow" /></button></div>; }
  function courseFeature() { return <article className="course-feature"><div className="course-feature-top"><div className="course-thumb" aria-hidden="true"><span>THE ONE<br />SYSTEM COURSE</span><strong>Guitar<br />Roadmap<br />2.0</strong><span className="big-one">1.</span></div><div className="course-description"><div className="eyebrow">已加入 · 系統課程</div><h2>The One<br />Guitar Roadmap 2.0</h2><p className="subtitle">你的吉他學習地圖，一步一步走得更遠。</p></div><div className="feature-cta"><Link className="btn primary" href={continueLink}><Icon name="play" />{learning.fresh ? "開始第一步" : "繼續學習"}</Link><Link className="text-button" href={studentHref("map")}>完整學習地圖<Icon name="arrowUpRight" /></Link></div></div><div className="stage-preview"><div className="stage-heading-row"><span className="title">我的階段旅程</span><span className="small muted">目前：Stage {learning.fresh ? 1 : 2}</span></div>{journey()}</div><div className="current-course-footer"><div className="current-title">{learning.fresh ? "已加入，從第一個階段開始。" : `目前課節：${currentLesson.title}`}</div>{progressLine()}<Link className="text-button" href={studentHref("map")}>查看課節<Icon name="right" /></Link></div></article>; }
  function privateLibrary() { return hasPrivate ? <section className="section"><div className="section-head"><div><h2>我的私人課</h2><p className="subtitle">一對一教學另外管理，不混在錄播課程進度裡。</p></div></div><div className="private-library-strip"><div className="teacher-avatar" aria-hidden="true">師</div><div className="grow"><strong>{teacherName}的一對一課程（示意）</strong><p>{learning.pack?.mode === "fixed" ? "固定制" : "預約制"} · 可預約 {learning.credit.available} 堂 · 已預留 {learning.credit.reserved} 堂{learning.nextBooking ? ` · 下一堂 ${d.date}` : ""}</p></div><Link className="text-button" href={studentHref("private")}>進入私人課<Icon name="arrow" /></Link></div></section> : null; }
  function privateLearning() { return <div className="private-learning"><section><h2 style={{ marginBottom: 12 }}>上課前，先練這些</h2>{[["把速度放慢，先穩定右手", "老師交代事項 · 示意"], ["錄一小段，帶著卡關處來上課", "不用完美，先讓老師聽到你的狀況。"]].map(([title, copy]) => <label className="practice-row" key={title}><input type="checkbox" checked={privateChecks.includes(title)} onChange={() => dispatch({ type: "privatePractice", studentId: student.id, practiceId: title })} /><span className="practice-copy">{title}<small>{copy}</small></span></label>)}{learning.enrolled ? <Link className="text-button" style={{ marginTop: 10 }} href={lessonHref("l3")}>對應課節：把切音放進伴奏<Icon name="arrowUpRight" /></Link> : <p className="micro" style={{ marginTop: 15 }}>你仍可上一對一課；不會因此自動加入吉他學習地圖。</p>}</section><section className="teacher-note"><Icon name="quote" /><p>{privateFeedback?.nextPractice || "先讓切音之後的下一拍穩定下來，不急著加快。下次上課，我們一起聽聽。"}</p><footer>— {teacherName} · 回饋版位示意，不是正式驗證結果</footer></section></div>; }
  function appointment() { return <section className="appointment"><div className="appointment-top"><span className={`mini-chip${learning.nextBooking ? " active" : ""}`}><Icon name="calendar" />{learning.nextBooking ? "下一堂私人課" : learning.credit.available ? "有堂數，尚未排課" : "本期已使用完畢"}</span>{learning.nextBooking && <span className="micro">已確認 · 範例預約</span>}</div>{learning.nextBooking ? <><div className="appointment-date"><div className="date-block"><div className="month">{d.month}</div><div className="day">{d.day}</div></div><div><div className="appointment-time">{d.time}</div><div className="appointment-desc">{d.weekday} · {zoneLabel(zone)}<br />線上課 · 50 分鐘</div></div></div><div className="appointment-heading">{student.focus}</div><div className="appointment-desc">{teacherName}（示意） · 上課前，先回顧上次的練習。</div><div className="appointment-action"><button className="btn primary" onClick={() => openModal("appointment")}>查看上課資訊<Icon name="arrow" /></button><button className="text-button" onClick={() => openModal("reschedule")}>需要調整時間？</button></div></> : <><h2 style={{ fontSize: 27, marginTop: 28 }}>{learning.credit.available ? <>為下一堂課，<br />留一段自己的時間。</> : <>回頭看看，<br />這段時間練了什麼。</>}</h2><p className="subtitle" style={{ margin: "15px 0 20px" }}>{learning.credit.available ? "已購買堂數，不等於已確認預約。選好時間後，下一堂課才會出現在這裡。" : "沒有可用堂數，也沒有待上的預約。舊有課程紀錄仍可查看。"}</p><div className="appointment-action"><button className="btn primary" onClick={() => learning.credit.available ? openModal("booking") : setPrivateTab("history")}><Icon name="calendar" />{learning.credit.available ? "挑選下一堂時間" : "查看上課紀錄"}</button><span className="micro">一堂 50 分鐘 · 示意</span></div></>}</section>; }
  function teacherSummary() { return <aside className="teacher-summary"><div className="row"><div className="teacher-avatar">師</div><div><div className="eyebrow" style={{ fontSize: 9, marginBottom: 7 }}>你的授課老師</div><h2>{teacherName}</h2><p className="subtitle">老師資料為版位示意</p></div></div><div className="service-mode"><h3>{learning.pack?.mode === "fixed" ? "固定制" : "預約制"}一對一課程</h3><p>{learning.pack?.mode === "fixed" ? <>固定時段示意：{fixedTime ? `每${fixedTime.weekday} ${fixedTime.time}（${zoneLabel(zone)}）` : "依已確認的固定安排顯示"}。<br />固定時段不是每一筆未來預約都已確認。</> : <>依你的時間選擇老師可預約的時段。<br />這是預約方式，不是會員方案或付款週期。</>}</p></div><div className="credit-summary"><span><strong>{learning.credit.available}</strong>可預約</span><span><strong>{learning.credit.reserved}</strong>已預留</span></div><button className="text-button" onClick={() => openModal("credits")}>查看這期堂數<Icon name="right" /></button><p className="micro" style={{ marginTop: 13 }}>一對一課程獨立於 Free / Plus / Pro；不從會員等級推定已購買私人課。</p></aside>; }
  function feedbackList(kind?: "private" | "pro") {
    const submissions = state.submissions.filter(item => item.studentId === student.id && (!kind || item.kind === kind));
    return <div className="student-feedback-grid">{submissions.map(item => { const reply = learning.feedback.find(f => f.submissionId === item.id); return <article className="teacher-note" key={item.id}><span className="mini-chip active">{item.kind === "pro" ? "平台 Pro 指導" : "私人課作業"} · {item.status === "replied" ? "老師已回覆" : item.status === "assigned" ? "已指派老師" : "待平台指派"}</span><h3 style={{ marginTop: 16 }}>{item.title}</h3><p className="subtitle">{item.question}</p>{reply && <><p style={{ marginTop: 20 }}>{reply.observation}</p><h3 style={{ marginTop: 16 }}>下一步怎麼練</h3><p>{reply.nextPractice}</p></>}<footer>{item.mediaName} · 示意提交，未作正式能力驗證</footer></article>; })}{submissions.length === 0 && <div className="empty"><h2>目前還沒有老師回饋。</h2><p>有實際課程關係或已取得的服務資格後，才在這裡顯示對應內容。</p></div>}</div>;
  }

  function settings() { return <>{pageHeader("MAKE IT YOURS / 你的使用習慣", "設定", "把學習空間，調成你舒服的樣子。")}<div className="settings-layout"><section className="setting-block"><h2>外觀</h2><p className="subtitle">白色、黑色，或跟著你的裝置。黃色仍然保留給重要的位置與操作。</p><div className="theme-choices" aria-label="外觀選擇">{(["light", "dark", "system"] as Theme[]).map(theme => <button className="theme-option" key={theme} aria-pressed={learning.theme === theme} onClick={() => learning.setTheme(theme)}><span className={`theme-swatch ${theme}`} aria-hidden="true"><span className="swatch-side"><i /><i /><i /></span><span className="swatch-main"><i /><span className="swatch-card" style={{ display: "block" }} /></span></span><span className="theme-name">{themeNames[theme]}<Icon name="check" /></span></button>)}</div><p className="setting-notice">主題切換套用學生、老師與管理員空間。<br />已核准錄播教室 v1.1 保留原版深色，不被新的樣式覆蓋。</p></section><section className="setting-block"><div className="setting-info"><div><h2>上課時間顯示</h2><p>私人課依你選的時區顯示同一個時間，不會另外產生一筆預約。</p></div><select className="setting-select" value={zone} onChange={event => setZone(event.target.value)} aria-label="顯示時區"><option value="Asia/Taipei">台北（UTC+8）</option><option value="Asia/Tokyo">東京（UTC+9）</option><option value="America/Los_Angeles">洛杉磯（依日期換算）</option></select></div></section><section className="setting-block"><div className="setting-info"><div><h2>學生守則</h2><p>依版本閱讀課程、預約與素材使用說明。示意已讀不是法律簽署。</p></div><Link className="btn secondary" href={studentHref("policies")}>查看學生守則<Icon name="right" /></Link></div></section><section className="setting-block"><div className="setting-info"><div><h2>這份 Demo 的資料</h2><p>示意資料由三端共用記憶體保存；重新整理重設。只有外觀偏好會嘗試存於瀏覽器。</p></div><button className="text-button" onClick={() => openModal("scenarios")}>切換學生情境<Icon name="right" /></button></div></section></div></>; }

  function content() {
    if (isGuidanceSubmit && (segments[1] !== "c1" || segments[3] !== "u1")) return <div className="empty"><h2>找不到這個課程單元</h2><Link className="btn primary" href={studentHref("map")}>回到學習地圖</Link></div>;
    switch (route) {
      case "today": return <>{pageHeader("WELCOME BACK / 歡迎回來", "今日學習", "今天不用練很多，先把下一步彈出來。")}<div className="today-top">{continueCard()}{practicePanel()}</div>{upcomingStrip()}{rails()}</>;
      case "courses": return <>{pageHeader("YOUR LEARNING / 已加入與已購課程", "我的課程", "這裡只放屬於你的學習，不把推薦混進來。")}<div className="tabs" role="tablist" aria-label="我的課程分類">{[["ongoing", "進行中", learning.enrolled ? "1" : "0"], ["completed", "已完成", "0"], ["private", "私人課", hasPrivate ? "1" : "0"]].map(([id, title, count]) => <button className={`tab${courseTab === id ? " active" : ""}`} role="tab" aria-selected={courseTab === id} key={id} onClick={() => setCourseTab(id)}>{title}<small>{count}</small></button>)}</div>{courseTab === "ongoing" ? <>{learning.enrolled ? courseFeature() : emptyCourse()}{privateLibrary()}</> : courseTab === "completed" ? <div className="empty"><Icon name="flag" /><h2>你的成果，會慢慢出現在這裡。</h2><p>目前沒有整套已完成的系統課程。单一課節自報完成，不會直接被當成整套結業或取得證書。</p><button className="btn secondary" onClick={() => setCourseTab("ongoing")}>回到進行中的課程</button></div> : hasPrivate ? privateLibrary() : <div className="empty"><h2>還沒有私人課</h2><Link className="btn secondary" href={studentHref("private")}>了解私人課</Link></div>}</>;
      case "map": { const s = stages[viewStage - 1]; return <>{pageHeader("THE ONE GUITAR ROADMAP 2.0 / 課程內導航", "我的學習地圖", "看見整條路，也知道現在這一步。", <Link className="text-button" href={studentHref("courses")}>我的課程<Icon name="right" /></Link>)} {!learning.enrolled ? emptyCourse() : <><div className="map-intro"><div><h2>你的階段旅程</h2><p className="subtitle">點選階段可以先看看；不會改變真正的學習位置。</p></div><span className="mini-chip active">目前 Stage {learning.fresh ? 1 : 2}</span></div><div className="map-stage-shell">{journey()}</div><div className="map-detail"><section className="map-outcome"><div className="eyebrow">STAGE {s.n} / {s.n === (learning.fresh ? 1 : 2) ? "目前階段" : "階段預覽"}</div><h2>{s.title}</h2><p>{s.copy}</p><div className="outcome-note">{s.n === 2 ? "這一站的目標：讓右手的停音、留白與節拍連在一起。" : "這是階段成果語言的示意。此階段的完整課綱，待正式內容確認後帶入。"}</div>{s.n === 2 ? <Link className="btn primary" href={lessonHref(currentLesson.id)}><Icon name="play" />回到目前課節</Link> : <button className="btn secondary" onClick={() => setViewStage(2)}>查看已製作的 Stage 2 範例</button>}</section><section>{s.n === 2 ? modules.map((name, m) => <div className="lesson-group" key={name}><h3>主題 {m + 1} · {name}</h3>{lessonVisuals.filter(l => l.module === m).map(l => <Link key={l.id} className={`mini-lesson${!learning.fresh && currentLesson.id === l.id ? " current" : ""}`} href={lessonHref(l.id)}><span className="no">{String(lessonVisuals.indexOf(l) + 1).padStart(2, "0")}</span><span><span className="lesson-row-title">{l.title}</span><small>{learning.done.includes(l.id) ? "已自報完成" : currentLesson.id === l.id ? "目前這一課" : "課節示意 · 未開始不是權限鎖"}</small></span><Icon className="state-icon" name={learning.done.includes(l.id) ? "check" : "playOutline"} /></Link>)}</div>) : <div className="empty" style={{ paddingTop: 8 }}><h3>先保留這段旅程的位置。</h3><p style={{ fontSize: 12, marginTop: 12 }}>本稿沒有捏造整套教材。現在可操作的是已確認的 Stage 2 三欄教室，以及對應的六個代表性課節。</p><button className="text-button" onClick={() => setViewStage(2)}>看看 Stage 2 的課節<Icon name="arrow" /></button></div>}</section></div></>}</>; }
      case "private": return <>{pageHeader("ONE-TO-ONE / 你的私人課", "私人課", "下一堂課、老師的提醒，都放在同一個地方。", <Link className="timezone" href={studentHref("settings")}><Icon name="globe" />{zoneLabel(zone)}</Link>)}{!hasPrivate ? <div className="empty"><Icon name="calendar" /><h2>想讓老師陪你練一段？</h2><p>私人課可以獨立購買。固定制保留穩定上課節奏；預約制依你的時間安排。你目前尚無已購私人課。</p><Link className="btn primary" href="/ux-prototype/#teachers">認識一對一老師<Icon name="arrow" /></Link></div> : <>{learning.packages.length > 1 && <label className="student-package-select">選擇我的課程包<select className="setting-select" value={learning.pack?.id} onChange={event => router.push(`${studentHref("private")}?package=${event.target.value}`)}>{learning.packages.map(pack => <option key={pack.id} value={pack.id}>{pack.snapshot.title} · {pack.source}</option>)}</select></label>}<div className="private-top">{appointment()}{teacherSummary()}</div><div className="tabs" role="tablist" aria-label="私人課內容">{[["next", "課前練習"], ["history", "上課紀錄"], ["feedback", "老師回饋"]].map(([id, title]) => <button className={`tab${privateTab === id ? " active" : ""}`} role="tab" key={id} aria-selected={privateTab === id} onClick={() => setPrivateTab(id)}>{title}</button>)}</div>{privateTab === "next" ? privateLearning() : privateTab === "feedback" ? feedbackList("private") : <section>{state.lessonRecords.filter(record => record.studentId === student.id).map(record => <div className="history-item" key={record.id}><div className="history-date">教學紀錄 · 示意</div><div className="grow"><strong>{record.publicNote}</strong><p>下一次練習：{record.practice}</p></div></div>)}{learning.bookings.filter(b => b.status === "completed").map(b => <div className="history-item" key={b.id}><div className="history-date">{dateInfo(b.start, zone).date}</div><div className="grow"><strong>{student.focus}</strong><p>已上課 · 線上私人課 · 示例紀錄</p></div></div>)}<p className="micro" style={{ marginTop: 17 }}>上課紀錄與系統課程自報進度分開，不會自動替學習地圖打勾。</p></section>}</>}</>;
      case "practice": return <>{pageHeader("PRACTICE / 把內容變成自己的", "我的練習", "先練一小段，也是一段前進。")} {learning.enrolled && !learning.fresh ? <div className="today-top">{practicePanel()}<div className="teacher-note"><Icon name="practice" /><h2>先穩定，再加一點變化。</h2><p className="subtitle" style={{ marginTop: 12 }}>今天的練習承接目前課節，不是另一套獨立課程。勾選只幫你記錄今天有沒有練，不會變成老師已驗證。</p><Link className="text-button" style={{ marginTop: 18 }} href={lessonHref(currentLesson.id)}>回到目前課節<Icon name="arrow" /></Link></div></div> : emptyCourse()}{hasPrivate && <><div className="hairline" /><div className="section">{privateLearning()}</div></>}</>;
      case "feedback": return <>{pageHeader("FEEDBACK / 把建議帶進下一次練習", "師生回饋", "分清楚來自哪一堂課，再看下一步。")}<div className="tabs"><button className="tab active">私人課回饋</button><Link className="tab" href={studentHref("guidance")}>平台 Pro 指導</Link></div>{hasPrivate && privateLearning()}<div className="section">{feedbackList("private")}</div>{state.platformReplies.filter(reply => reply.studentId === student.id).map(reply => <article className="teacher-note" key={reply.id}><h3>{reply.authorLabel}</h3><p>{reply.body}</p></article>)}</>;
      case "settings": return settings();
      case "policies": return <>{pageHeader("LEARNING AGREEMENT / 學習前先知道", "學生守則", "這是本機守則草案，標記已讀不代表正式簽約。")}{state.policies.filter(policy => policy.audience === "student").map(policy => { const ack = state.acknowledgements.some(item => item.actorId === student.id && item.policyId === policy.id && item.version === policy.version); return <section className="setting-block" key={policy.id}><span className="mini-chip">草案 · {policy.version}</span><h2 style={{ marginTop: 15 }}>{policy.title}</h2><p style={{ whiteSpace: "pre-wrap", margin: "20px 0" }}>{policy.body}</p><button className="btn primary" disabled={ack} onClick={() => { const result = dispatch({ type: "ackPolicy", policyId: policy.id }); setNotice(result.ok ? "已標記目前版本已讀，這不是法律簽署。" : result.error || "無法標記"); }}>{ack ? "目前版本已讀" : "我已閱讀此版本 · 示意"}</button></section>; })}</>;
      case "guidance": return <>{pageHeader(isGuidanceSubmit ? "STUDENT FLOW / 單元最後一步・新增提案" : "YOUR FEEDBACK / 每一次練習都有下一步", isGuidanceSubmit ? "讓老師看看你的練習。" : "本次指導進度", "吉他學習地圖 › Stage 2 › 右手節奏與切音。此頁不改動已核准播放器。")}<GuidanceContent submit={isGuidanceSubmit} /></>;
      default: return <div className="empty"><h2>找不到這個學生頁面</h2><Link href={studentHref()} className="btn primary">回到今日學習</Link></div>;
    }
  }

  function modalBody() {
    switch (modal) {
      case "intro": return <><span className="mini-chip active">旗艦系統課程 · 不是會員方案</span><p className="dialog-copy">從「把一首歌彈完」開始，透過階段、主題、課節與練習，知道自己在哪裡，以及下一步去哪裡。</p><div className="simple-list"><p>看課程結構 → 明確加入 → 在「我的課程」看見個人進度。</p><p>Free / Plus / Pro 是平台會員方案，各項內容能否使用仍依課程政策與有效資格決定。</p></div><div className="dialog-actions">{learning.enrolled ? <button className="btn primary" onClick={() => go("courses")}>前往我的課程</button> : <button className="btn primary" onClick={join}>加入學習 · 僅本機示意</button>}<Link className="btn secondary" href={lessonHref()}>預覽已定稿教室</Link></div></>;
      case "search": return <><input className="search-field" value={search} onChange={event => setSearch(event.target.value)} autoFocus aria-label="輸入課節關鍵字" placeholder="試試「切音」、「伴奏」或「拍子」" /><div className="search-results">{lessonVisuals.filter(l => (l.title + l.note).includes(search.trim())).map(l => <Link className="search-result" href={lessonHref(l.id)} key={l.id}><Icon name="playOutline" /><span>{l.title}<small>吉他學習地圖 / Stage 2 / 第 {lessonVisuals.indexOf(l) + 1} 課</small></span><Icon name="right" className="spacer" /></Link>)}{!lessonVisuals.some(l => (l.title + l.note).includes(search.trim())) && <p className="dialog-copy">沒有找到符合的示範課節，試試其他關鍵字。</p>}</div></>;
      case "credits": return <><p className="dialog-copy">{teacherName}（示意） · {learning.pack?.mode === "fixed" ? "固定制" : "預約制"}<br />堂數與預約分開看：已預留不等於已上完。</p><div className="simple-list"><p>本期總數：{learning.credit.allocated} 堂</p><p>可再預約：{learning.credit.available} 堂</p><p>已為預約保留：{learning.credit.reserved} 堂</p><p>已上課：{learning.credit.consumed} 堂</p></div><p className="dialog-note">已購版本：{learning.pack?.offerVersion}；價格快照不因老師更新公開課包而改動。</p>{learning.pack?.mode === "flexible" && learning.credit.available > 0 && <button className="btn primary" onClick={() => openModal("booking")}>挑選下一堂時間</button>}</>;
      case "appointment": return <><span className="mini-chip active">已確認 · 範例資料</span><h3 style={{ marginTop: 17 }}>{student.focus}</h3><div className="simple-list"><p>{d.date}<br />{d.time} · {zoneLabel(zone)}</p><p>授課老師：{teacherName}（示意）<br />上課方式：線上 · 50 分鐘</p><p>預約編號：{learning.nextBooking?.id}</p><p>教室連結與課前資料會放在這裡。本 Demo 沒有真實視訊連結。</p></div></>;
      case "reschedule": return <><p className="dialog-copy">你可以提出單堂改期或取消。適用規則、可用時段與堂數結果仍須由正式服務確認。</p><p className="dialog-copy">目前可確認資料與時間偏好；固定系列不會跟著改動。</p><Link className="btn primary" href={studentHref(`bookings/${learning.nextBooking?.id}/change`)} onClick={closeModal}>調整這堂預約</Link></>;
      case "booking": return <><p className="dialog-copy">{teacherName}（示意） · 預約制 · 線上 50 分鐘<br />顯示為{zoneLabel(zone)}。只预留一堂，不扣已上課堂數。</p>{confirmBooking ? <><span className="mini-chip active">確認這個時段</span><p className="dialog-copy">{dateInfo(learning.slots.find(item => item.id === slot)?.start, zone).date} · {dateInfo(learning.slots.find(item => item.id === slot)?.start, zone).time}</p><p className="dialog-copy">影響：可預約 {learning.credit.available} → {learning.credit.available - 1}，已預留 {learning.credit.reserved} → {learning.credit.reserved + 1}。不產生付款、已上課或老師收入。</p><div className="dialog-actions"><button className="btn primary" onClick={() => { if (!learning.pack) return; const result = dispatch({ type: "book", packageId: learning.pack.id, slotId: slot, consent: "學生已親自選擇並確認此線上時段", policyConfirmed: true, confirmed: true, reason: "學生本機示意預約", requestId: `student-${student.id}-${slot}` }); if (result.ok) { closeModal(); setNotice(`示意預約 ${result.id} 已建立，三端共用同一筆資料。`); } else setNotice(result.error || "無法預約"); }}>確認示範預約</button><button className="btn secondary" onClick={() => setConfirmBooking(false)}>重新選擇</button></div></> : <><div className="slot-options">{learning.slots.map(item => { const info = dateInfo(item.start, zone); return <button className="slot-option" key={item.id} aria-pressed={slot === item.id} onClick={() => setSlot(item.id)}>{info.date}<br />{info.time}</button>; })}</div>{!learning.slots.length && <p className="dialog-copy">目前沒有符合資格的可用時段。固定制不在這個入口修改系列。</p>}<button className="btn primary" disabled={!slot} onClick={() => setConfirmBooking(true)}>預覽本次預約影響</button></>}</>;
      case "scenarios": return <div className="dialog-form"><p className="dialog-copy">隔離 Mock 情境工具，不登入、不付款、不改正式帳號。</p><label>示意學生<select aria-label="示意學生" value={student.id} onChange={event => learning.setStudentId(event.target.value)}>{state.students.map(s => <option value={s.id} key={s.id}>{s.name} · {s.id}</option>)}</select></label><label>平台會員<select aria-label="平台會員" value={student.membership} onChange={event => dispatch({ type: "setStudentScenario", studentId: student.id, membership: event.target.value as Membership })}>{["Free", "Plus", "Pro"].map(v => <option key={v}>{v}</option>)}</select></label><label>系統課程<select aria-label="系統課程" value={learning.enrolled ? "joined" : "none"} onChange={event => dispatch({ type: "setStudentScenario", studentId: student.id, joined: event.target.value === "joined" })}><option value="joined">已明確加入</option><option value="none">尚未加入（私人課仍獨立）</option></select></label><label>本課存取<select aria-label="本課存取" value={student.accessCourseIds.includes("c1") ? "yes" : "no"} onChange={event => dispatch({ type: "setStudentScenario", studentId: student.id, access: event.target.value === "yes" })}><option value="yes">有示意存取資格</option><option value="no">無存取資格</option></select></label><label>Pro 服務资格<select aria-label="Pro 服務资格" value={student.serviceEligibility} onChange={event => dispatch({ type: "setStudentScenario", studentId: student.id, serviceEligibility: event.target.value as "available" | "unavailable" | "unknown" })}><option value="available">本次可用</option><option value="unknown">待確認</option><option value="unavailable">本次不可用</option></select></label></div>;
      default: return null;
    }
  }
  const modalTitles: Record<string, string> = { intro: "The One Guitar Roadmap 2.0", search: "找一段，現在想練的內容", credits: "這一期的一對一堂數", appointment: "下一堂私人課", reschedule: "調整上課時間", booking: "選一段，可以專心上課的時間", scenarios: "切換學生情境" };
  const navLinks = studentNav.map(([id, icon, title]) => <Link className={`nav-button${route === id ? " current" : ""}`} href={studentHref(id)} key={id} aria-current={route === id ? "page" : undefined} aria-label={title} onClick={() => menu.current?.close()}><Icon name={icon} /><span className="nav-text">{title}</span><span className="nav-tip">{title}</span></Link>);

  return <div className="ux-student" data-theme={effectiveTheme} data-testid="student-surface"><div className={`app${collapsed ? " collapsed" : ""}`}><aside className="sidebar"><Link className="brand" href="/ux-prototype"><BrandLogo compact={collapsed} /></Link><div className="nav-group-label">你的學習空間</div><nav className="mainnav" aria-label="學生主要導覽">{navLinks}</nav><div className="nav-divider" /><button className="nav-button" onClick={() => openModal("search")} aria-label="搜尋課節"><Icon name="search" /><span className="nav-text">搜尋課節</span><span className="nav-tip">搜尋課節</span></button><div className="nav-bottom"><Link className={`nav-button${route === "settings" ? " current" : ""}`} href={studentHref("settings")} aria-label="設定"><Icon name="settings" /><span className="account-text nav-text">設定<small>外觀：{themeNames[learning.theme]}</small></span></Link><Link className="nav-button account-row" href="/ux-prototype/account" aria-label="我的帳戶"><span className="user-dot">你</span><span className="account-text nav-text">練習中的你<small>帳戶與會員</small></span></Link><button className="nav-button collapse-btn" aria-expanded={!collapsed} aria-label={collapsed ? "展開選單" : "收合選單"} onClick={() => setCollapsed(!collapsed)}><Icon name="expand" /><span className="nav-text">收合選單</span></button></div></aside><header className="mobile-header"><Link className="brand" href="/ux-prototype"><BrandLogo size="small" /></Link><div className="mobile-actions"><button className="icon-button" aria-label="搜尋課節" onClick={() => openModal("search")}><Icon name="search" /></button><button className="icon-button" aria-label="開啟學生選單" onClick={() => menu.current?.showModal()}><Icon name="menu" /></button></div></header><main className="main" key={route}><div className="page">{content()}<p className="footnote">僅供版面與操作確認：課名、階段、進度、老師與日期均為示意；不是正式課綱或服務承諾。只展示一套系統課程，不代表其他課程已上架。</p></div></main></div>
    <dialog ref={menu} className="mobile-dialog" aria-label="學生選單"><div className="dialog-header"><h2><BrandLogo size="small" /></h2><button className="icon-button" aria-label="關閉學生選單" onClick={() => menu.current?.close()}><Icon name="close" /></button></div>{navLinks}<div className="nav-divider" /><Link className="nav-button" href="/ux-prototype/account" onClick={() => menu.current?.close()}>我的帳戶與會員</Link><Link className="nav-button" href="/ux-prototype/account/notifications" onClick={() => menu.current?.close()}>通知與回饋</Link><Link className="nav-button" href={studentHref("settings")} onClick={() => menu.current?.close()}><Icon name="settings" /><span className="nav-text">外觀與設定</span></Link></dialog>
    <dialog ref={dialog} onClose={() => setModal(null)} aria-labelledby="student-modal-title"><div className="dialog-header"><h2 id="student-modal-title">{modal ? modalTitles[modal] : ""}</h2><button className="icon-button" aria-label="關閉對話框" onClick={closeModal}><Icon name="close" /></button></div>{modalBody()}<div className="dialog-actions"><button className="btn secondary" onClick={closeModal}>返回</button></div></dialog>{notice && <div className="toast" role="status">{notice}</div>}
  </div>;
}

function dateInfo(iso: string | undefined, zone: string) {
  const date = new Date(iso || "2026-09-12T12:00:00Z");
  const parts = new Intl.DateTimeFormat("zh-TW", { timeZone: zone, year: "numeric", month: "numeric", day: "numeric", weekday: "long", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(date);
  const get = (name: string) => parts.find(p => p.type === name)?.value || "";
  const end = new Intl.DateTimeFormat("zh-TW", { timeZone: zone, hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(date.getTime() + 50 * 60_000));
  return { date: new Intl.DateTimeFormat("zh-TW", { timeZone: zone, month: "numeric", day: "numeric", weekday: "short" }).format(date), time: `${get("hour")}:${get("minute")}–${end}`, month: new Intl.DateTimeFormat("zh-TW", { timeZone: zone, year: "numeric", month: "long" }).format(date), day: get("day"), weekday: get("weekday") };
}
function zoneLabel(zone: string) { return ({ "Asia/Taipei": "台北時間 UTC+8", "Asia/Tokyo": "東京時間 UTC+9", "America/Los_Angeles": "洛杉磯時間" } as Record<string, string>)[zone] || zone; }
