import { PageShell, PrimaryCTA, SectionHeader, ResourceRow } from "@/components/learning/ui";
import { GuitarArt } from "@/components/learning/guitar-art";
import { learningPreview } from "@/lib/preview/learning";
export default function GuitarRoadmap() {
 return <PageShell><section className="course-hero"><div><p className="eyebrow">旗艦 SYSTEM COURSE / GUITAR</p><h1>The One<br/>Guitar Roadmap <em>2.0</em></h1><p className="hero-statement">從喜歡吉他，<br/>一路走到真正能自己彈出音樂。</p><p className="body-copy">不再用看過多少影片，衡量自己的進步。<br/>一起把節奏、和弦與聽見的音樂，慢慢變成你的能力。</p><div className="cta-row"><PrimaryCTA href="/student/map">探索學習地圖</PrimaryCTA><PrimaryCTA secondary href="#journey">看看這段旅程</PrimaryCTA></div></div><GuitarArt/></section>
 <section className="section audience"><SectionHeader eyebrow="THIS JOURNEY IS FOR YOU" title="有一點基礎，或正準備開始。"/><div className="three-columns"><p>會彈幾首歌，<strong>卻不知道怎麼更進一步。</strong></p><p>想把伴奏彈得更好聽，<strong>也想理解手上的音樂。</strong></p><p>每天只有一點時間，<strong>希望每一次練習都有方向。</strong></p></div></section>
 <section className="section journey-section" id="journey"><SectionHeader eyebrow="LEARN → PRACTICE → APPLY → VERIFY" title="每一站，都是一個「我可以」。"/><div className="outcome-journey">{learningPreview.stages.map((title,i)=><div key={title}><span>LEVEL 0{i+1}</span><h3>{title}</h3></div>)}</div><p className="muted">以上保留既有 Level 成果方向；地圖內的課節與進度為 UX 示範，並非正式 curriculum 或能力認證。</p></section>
 <section className="section two-columns"><div><SectionHeader eyebrow="MORE WAYS TO UNDERSTAND" title="看懂之後，還有練會的路。" text="示範、圖解、音檔與伴奏，是幫助你理解與應用的不同方式；不是每一課都需要固定的資源組合。"/><ResourceRow kind="PDF" title="帶著圖解，拆解每個動作" detail="教材展示 · 非正式下載"/><ResourceRow kind="♫" title="跟著音樂，把節奏放進身體" detail="音檔 / backing track 展示"/></div><div className="support-panel"><p className="eyebrow">YOUR PACE. YOUR SUPPORT.</p><h2>自己練，也有人陪。</h2><p>Free 找方向，Plus 建立自主練習的系統，Pro 加上人工回饋與驗證。課程存取仍依正式會員與權益政策決定。</p><p>遇到卡關，老師與私人課程可以成為下一步的支持。</p><PrimaryCTA secondary href="/teachers">找到適合的老師</PrimaryCTA></div></section>
 <section className="closing-cta"><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>下一次拿起吉他，<br/>知道自己為什麼而練。</h2><PrimaryCTA href="/student">看看我的學習首頁</PrimaryCTA></section></PageShell>;
}
