"use server";
import "server-only";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requireAreaAccess } from "@/modules/auth/server-authorization";
import {adminOrderSchema,adminPaymentSchema,bankTransferSchema,cashPaymentSchema,checkoutSchema} from "@/modules/commerce/domain";
const read=(f:FormData,k:string)=>typeof f.get(k)==="string"?String(f.get(k)):"";
export async function createCheckoutOrder(f:FormData){await requireAreaAccess("student");const p=checkoutSchema.safeParse({productSlug:read(f,"productSlug"),quantity:read(f,"quantity"),idempotencyKey:read(f,"idempotencyKey")});if(!p.success)redirect("/products?error=invalid_checkout");const s=await createServerSupabaseClient();const {data,error}=await s.rpc("create_checkout_order",{p_product_slug:p.data.productSlug,p_quantity:p.data.quantity,p_idempotency_key:p.data.idempotencyKey});if(error||!data)redirect(`/products/${p.data.productSlug}?error=checkout_failed`);redirect(`/student/orders/${data}`);}
export async function submitBankTransfer(f:FormData){await requireAreaAccess("student");const p=bankTransferSchema.safeParse({orderId:read(f,"orderId"),payerName:read(f,"payerName"),transferLast5:read(f,"transferLast5"),note:read(f,"note"),idempotencyKey:read(f,"idempotencyKey")});if(!p.success)redirect("/student/orders?error=invalid_payment");const s=await createServerSupabaseClient();const {error}=await s.rpc("submit_bank_transfer",{p_order_id:p.data.orderId,p_payer_name:p.data.payerName,p_transfer_last5:p.data.transferLast5,p_payment_note:p.data.note||null,p_idempotency_key:p.data.idempotencyKey});if(error)redirect(`/student/orders/${p.data.orderId}?error=submit_failed`);revalidatePath(`/student/orders/${p.data.orderId}`);redirect(`/student/orders/${p.data.orderId}?status=submitted`);}
export async function cancelOwnOrder(f:FormData){await requireAreaAccess("student");const p=adminOrderSchema.safeParse({orderId:read(f,"orderId"),reason:read(f,"reason")||"Buyer requested cancellation"});if(!p.success)redirect("/student/orders?error=invalid_order");const s=await createServerSupabaseClient();const {error}=await s.rpc("cancel_own_order",{p_order_id:p.data.orderId,p_reason:p.data.reason});if(error)redirect(`/student/orders/${p.data.orderId}?error=cancel_failed`);redirect(`/student/orders/${p.data.orderId}?status=cancelled`);}
export async function adminConfirmPayment(f:FormData){await requireAreaAccess("admin");const p=adminPaymentSchema.safeParse({orderId:read(f,"orderId"),paymentId:read(f,"paymentId"),reason:read(f,"reason")});if(!p.success)redirect("/admin/orders?error=invalid_payment");const s=await createServerSupabaseClient();const {error}=await s.rpc("admin_confirm_payment",{p_order_id:p.data.orderId,p_payment_id:p.data.paymentId,p_provider_event_id:null,p_reason:p.data.reason});if(error)redirect(`/admin/orders/${p.data.orderId}?error=confirm_failed`);redirect(`/admin/orders/${p.data.orderId}?status=paid`);}
export async function adminRejectPayment(f:FormData){await requireAreaAccess("admin");const p=adminPaymentSchema.safeParse({orderId:read(f,"orderId"),paymentId:read(f,"paymentId"),reason:read(f,"reason")});if(!p.success)redirect("/admin/orders?error=invalid_payment");const s=await createServerSupabaseClient();const {error}=await s.rpc("admin_reject_payment_submission",{p_payment_id:p.data.paymentId,p_reason:p.data.reason});if(error)redirect(`/admin/orders/${p.data.orderId}?error=reject_failed`);redirect(`/admin/orders/${p.data.orderId}?status=rejected`);}
export async function adminConfirmCash(f:FormData){await requireAreaAccess("admin");const p=cashPaymentSchema.safeParse({orderId:read(f,"orderId"),idempotencyKey:read(f,"idempotencyKey"),reason:read(f,"reason")});if(!p.success)redirect("/admin/orders?error=invalid_payment");const s=await createServerSupabaseClient();const {error}=await s.rpc("admin_confirm_cash_payment",{p_order_id:p.data.orderId,p_idempotency_key:p.data.idempotencyKey,p_reason:p.data.reason});if(error)redirect(`/admin/orders/${p.data.orderId}?error=cash_failed`);redirect(`/admin/orders/${p.data.orderId}?status=paid`);}
export async function adminCancelOrder(f:FormData){await requireAreaAccess("admin");const p=adminOrderSchema.safeParse({orderId:read(f,"orderId"),reason:read(f,"reason")});if(!p.success)redirect("/admin/orders?error=invalid_order");const s=await createServerSupabaseClient();const {error}=await s.rpc("admin_cancel_order",{p_order_id:p.data.orderId,p_reason:p.data.reason});if(error)redirect(`/admin/orders/${p.data.orderId}?error=cancel_failed`);redirect(`/admin/orders/${p.data.orderId}?status=cancelled`);}
