import "server-only";

import { createPrivilegedSupabaseClient } from "@/lib/supabase/admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requireAreaAccess } from "@/modules/auth/server-authorization";

export type CatalogProduct={productId:string;slug:string;name:string;description:string|null;shortDescription:string|null;currency:string;price:number;type:string;seller:string;purchasable:boolean};
type PaymentSummary={id:string;method:string;status:string;amount:number;currency:string;paid_at:string|null;submission_status:string|null};
export async function listPublicProducts():Promise<CatalogProduct[]> { const s=await createServerSupabaseClient(); const {data}=await s.from("product_public_catalog").select("product_id,public_slug,name,description,short_description,currency,base_price_amount,product_type,seller_display_name,is_purchasable").order("published_at",{ascending:false}); return (data??[]).map(r=>({productId:r.product_id,slug:r.public_slug,name:r.name,description:r.description,shortDescription:r.short_description,currency:r.currency,price:r.base_price_amount,type:r.product_type,seller:r.seller_display_name,purchasable:r.is_purchasable})); }
export async function getPublicProduct(slug:string){return (await listPublicProducts()).find(p=>p.slug===slug)??null;}
export async function listOwnOrders(){await requireAreaAccess("student");const s=await createServerSupabaseClient();const {data}=await s.from("orders").select("id,order_number,status,currency,total_amount,payment_status,created_at").order("created_at",{ascending:false});return data??[];}
export async function getOwnOrder(id:string){await requireAreaAccess("student");const s=await createServerSupabaseClient();const [order,items,payments]=await Promise.all([s.from("orders").select("id,order_number,status,currency,subtotal_amount,discount_amount,tax_amount,total_amount,payment_status,expires_at,paid_at,cancelled_at,created_at").eq("id",id).maybeSingle(),s.from("order_items").select("id,product_name_snapshot,product_type_snapshot,unit_price_amount,quantity,line_total_amount").eq("order_id",id),s.rpc("get_own_payment_summaries",{p_order_id:id})]);if(!order.data)return null;return {order:order.data,items:items.data??[],payments:(payments.data??[]) as PaymentSummary[]};}
export async function listAdminOrders(){await requireAreaAccess("admin");const s=createPrivilegedSupabaseClient();const {data}=await s.from("orders").select("id,order_number,buyer_user_id,status,currency,total_amount,payment_status,created_at,profiles!orders_buyer_user_id_fkey(display_name),order_items(product_name_snapshot,quantity)").order("created_at",{ascending:false});return (data??[]).map(row=>({...row,buyerDisplayName:row.profiles[0]?.display_name}));}
export async function getAdminOrder(id:string){await requireAreaAccess("admin");const s=createPrivilegedSupabaseClient();const [order,items,payments,submissions]=await Promise.all([s.from("orders").select("*").eq("id",id).maybeSingle(),s.from("order_items").select("*").eq("order_id",id),s.from("payments").select("id,provider,method,status,amount,currency,paid_at,failed_at,created_at").eq("order_id",id),s.from("payment_submissions").select("id,payment_id,payer_name,transfer_last5,payment_note,status,submitted_at,reviewed_at,review_reason").eq("order_id",id)]);if(!order.data)return null;return {order:order.data,items:items.data??[],payments:payments.data??[],submissions:submissions.data??[]};}
