"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { usePrototype } from "@/modules/ux-prototype/store";
import { availableSlots, balance, canOperate, policiesAccepted, visibleAudit, visibleSubmissions, type Booking, type BookingMode, type StudentPackage } from "@/modules/ux-prototype/model";
import { Area, Btn, Check, Empty, Field, Flag, Foot, Go, Header, Icon, Modal, Select, Table, dateTime, modeName, statusName, useWorkspaceActions } from "./shared";

export function BookingForm({role,booking,onDone}:{role:"teacher"|"admin";booking?:Booking;onDone?:()=>void}) {
  const {state,actor,dispatch,timeZone:zone}=usePrototype();const {notify,confirm}=useWorkspaceActions();const query=useSearchParams();
  const eligible=state.packages.filter(pack=>role==="admin"||(pack.teacherId===actor.id&&pack.mode==="flexible"&&state.students.some(student=>student.id===pack.studentId&&student.teacherId===actor.id&&student.relation==="private")));
  const students=state.students.filter(student=>eligible.some(pack=>pack.studentId===student.id));const [studentId,setStudentId]=useState(booking?.studentId||students.find(item=>item.id===query.get("student"))?.id||students[0]?.id||"");const packs=eligible.filter(item=>item.studentId===studentId);const [chosenPackage,setPackage]=useState(booking?.packageId||"");const pack=packs.find(item=>item.id===chosenPackage)||packs[0];const [slotId,setSlot]=useState("");const [consent,setConsent]=useState("");const [reason,setReason]=useState("");const [ack,setAck]=useState(false);
  const slots=pack?availableSlots(state,pack.id,actor,booking?.id):[];const slot=slots.find(item=>item.id===slotId);const credit=pack?balance(state,pack.id):null;const student=state.students.find(item=>item.id===studentId);const fmt=(value:string)=>new Intl.DateTimeFormat("zh-TW",{timeZone:zone,month:"numeric",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));
  function preview(){if(!pack||!slot||!ack||consent.trim().length<3||reason.trim().length<3)return notify("請選擇有效課程包與可約時段，填寫同意依據、原因，並勾選確認。");if(role==="teacher"&&!policiesAccepted(state,actor))return notify("請先到老師合作守則閱讀目前完整版本。");const packageId=pack.id,selectedSlot=slot.id;confirm(booking?"確認示意改期":"確認代約・只預留一堂",<><h3>{student?.name} · {pack.snapshot.title}</h3><p>{fmt(slot.start)} · {zone} · 線上 50 分鐘</p><p>學生同意依據：{consent}</p><p>原因：{reason}</p><p>{booking?"已預留堂數保持不變。":`可預約 ${credit!.available} → ${credit!.available-1}；已預留 ${credit!.reserved} → ${credit!.reserved+1}。`} 已上課、付款和老師收入不變。</p></>,()=>{const result=dispatch(booking?{type:"reschedule",bookingId:booking.id,slotId:selectedSlot,consent,reason,confirmed:true,requestId:`reschedule-${booking.id}-${selectedSlot}-${state.counter}`}:{type:"book",packageId,slotId:selectedSlot,consent,reason,policyConfirmed:ack,confirmed:true,requestId:`book-${packageId}-${selectedSlot}-${state.counter}`});notify(result.ok?`示意預約 ${result.id} 已更新；學生、老師、管理員共用這筆資料。`:result.error!);if(result.ok){setSlot("");onDone?.()}return result.ok})}
  return <><div className="v4-alert">代預約不是代上課。先取得學生對具體時段的同意，再選有效課程包；成功後只預留一堂，不消耗、不產生老師報酬。</div><div className="v4-editor"><section><Select label={role==="teacher"?"有教學關係的預約制學生":"受益學生"} value={studentId} disabled={Boolean(booking)} onChange={value=>{setStudentId(value);setPackage("");setSlot("")}} options={students.map(item=>[item.id,item.name])}/><Select label="使用這個學生的課程包" value={pack?.id||""} disabled={Boolean(booking)} onChange={value=>{setPackage(value);setSlot("")}} options={packs.map(item=>[item.id,`${item.snapshot.title} · ${modeName(item.mode)} · 可用 ${balance(state,item.id).available} 堂`])}/><h3 style={{margin:"26px 0 15px"}}>可預約的線上時段</h3><p className="micro" style={{marginBottom:15}}>{zone==="Asia/Taipei"?"台北時間 UTC+8":zone} · 以 {state.clock.slice(0,10)} 示意時鐘檢查；不開放實體。</p>{slots.length?<div className="v4-slot-grid">{slots.map(item=><button type="button" className={`v4-slot ${slotId===item.id?"active":""}`} key={item.id} aria-pressed={slotId===item.id} onClick={()=>setSlot(item.id)}><b>{fmt(item.start)}</b><small>線上課 · 50 分鐘 · {modeName(item.mode)}</small></button>)}</div>:<Empty title="目前沒有相容的可約時段">請確認堂數、老師、效期或時段衝突，不會用代約繞過限制。</Empty>}<div style={{marginTop:28}}><Area label="學生同意的依據（必填）" value={consent} onChange={setConsent}/><Area label="代約原因（必填）" value={reason} onChange={setReason}/><Check label="學生已同意本次具體時段，且我已閱讀代約守則" checked={ack} onChange={setAck}/></div><Btn primary onClick={preview}>檢查並預覽預約</Btn></section><aside className="v4-guide"><h3>這次使用的權益</h3>{pack&&credit?<>{[["學生",student?.name],["可預約",`${credit.available} 堂`],["已預留",`${credit.reserved} 堂`],["上課方式","僅線上"],["課程包有效至",pack.expiry]].map(([label,value])=><div className="v4-fact" key={label}><span>{label}</span><b>{value}</b></div>)}</>:<p>先選擇有可用堂數的學生。</p>}<p>同老師與同學生的時間衝突都會檢查。一次代約不會變成固定系列。</p><Go to={`${role}/policies`}>閱讀{role==="teacher"?"老師合作":"平台"}守則</Go></aside></div></>;
}
export function TeacherBooking() {return <><Header eyebrow="BOOK TOGETHER / 先與學生確認，再把時段留好" title="幫學生預約" sub="僅限自己的線上一對一「預約制」學生，固定制系列交由原排課流程處理。"/><BookingForm role="teacher"/><Foot/></>}

export function AdminBookings() {
  const {state,timeZone:zone}=usePrototype();const displayZone=zone==="Asia/Taipei"?"台北 UTC+8":zone==="Asia/Tokyo"?"東京 UTC+9":"洛杉磯";const [edit,setEdit]=useState<Booking|"new"|null>(null);const [cancel,setCancel]=useState<Booking|null>(null);
  return <><Header eyebrow="BOOKING OPERATIONS / 把時間和權益一起確認" title="預約管理" sub="代預約仍需有效課程包、可用堂數與無衝突時段。" tools={<Btn primary onClick={()=>setEdit("new")}>＋ 代學生預約</Btn>}/><Table headers={["學生／老師",`時間・${displayZone}`,"預約方式","狀態／使用課程包","操作"]}>{state.bookings.map(item=><tr key={item.id}><td><strong>{state.students.find(student=>student.id===item.studentId)?.name}</strong><small>{state.teachers.find(teacher=>teacher.id===item.teacherId)?.draft.name}</small></td><td>{dateTime(item.start,zone)}<small>預約編號 {item.id}</small></td><td>{modeName(item.mode)}</td><td><Flag active={item.status==="reserved"}>{statusName(item.status)}</Flag><small>{state.packages.find(pack=>pack.id===item.packageId)?.snapshot.title}</small></td><td>{item.status==="reserved"?<div className="x-actions"><Btn onClick={()=>setEdit(item)}>改期</Btn><Btn onClick={()=>setCancel(item)}>取消</Btn></div>:"—"}</td></tr>)}</Table><p className="footnote">固定時段優先權不是買了幾堂就產生幾個永久保留位。只比較已列出的單次時段，不生成循環排課。</p>{edit&&<Modal wide title={edit==="new"?"代學生預約":"改期示意預約"} onClose={()=>setEdit(null)}><BookingForm role="admin" booking={edit==="new"?undefined:edit} onDone={()=>setEdit(null)}/></Modal>}{cancel&&<CancelBooking booking={cancel} close={()=>setCancel(null)}/>}<Foot/></>;
}
function CancelBooking({booking,close}:{booking:Booking;close:()=>void}) {
  const {dispatch,state,timeZone:zone}=usePrototype();const {notify,confirm}=useWorkspaceActions();const [reason,setReason]=useState("");
  return <Modal title="取消這筆示意預約" onClose={close}><p className="x-copy">{state.students.find(item=>item.id===booking.studentId)?.name} · {dateTime(booking.start,zone)}</p><p>取消會釋放 1 堂預留，不產生退款或完成上課。</p><Area label="取消原因（必填）" value={reason} onChange={setReason}/><Btn primary onClick={()=>{if(reason.trim().length<3)return notify("請填寫至少三個字的具體原因。");confirm("確認取消並釋放預留堂數",<><p>{dateTime(booking.start,zone)} · 預約 {booking.id}</p><p>{reason}</p><p>釋放預留 1 堂；沒有真實退款。</p></>,()=>{const result=dispatch({type:"cancelBooking",bookingId:booking.id,reason,confirmed:true,requestId:`cancel-${booking.id}`});notify(result.ok?"預約已取消，預留堂數已釋放。":result.error!);if(result.ok)close();return result.ok})}}>預覽取消影響</Btn></Modal>;
}
export function AdminStudents() {
  const {state}=usePrototype();const [query,setQuery]=useState("");const [grant,setGrant]=useState(false);const [detail,setDetail]=useState<string|null>(null);const student=state.students.find(item=>item.id===detail);
  return <><Header eyebrow="STUDENTS & ACCESS / 看見需要協助的地方" title="學生與權益" sub="會員方案、已加入課程與一對一課程包，分開查看。"/><div className="x-action-bar"><Field label="搜尋示意學生" value={query} onChange={setQuery} placeholder="搜尋學生姓名"/><Btn primary onClick={()=>setGrant(true)}>新增課程包</Btn></div><Table headers={["學生","平台會員","已加入課程","一對一堂數","操作"]}>{state.students.filter(item=>item.name.includes(query)).map(item=>{const packs=state.packages.filter(pack=>pack.studentId===item.id);return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.membership}</td><td>{item.joinedCourseIds.map(id=>state.courses.find(course=>course.id===id)?.published?.title).filter(Boolean).join("、")||"尚未加入系統課程"}</td><td>{packs.length?packs.map(pack=><small key={pack.id}>{modeName(pack.mode)} · 可預約 {balance(state,pack.id).available}／已預留 {balance(state,pack.id).reserved}</small>):"沒有一對一課程包"}</td><td><Btn onClick={()=>setDetail(item.id)}>查看權益</Btn></td></tr>})}</Table>{!state.students.some(item=>item.name.includes(query))&&<Empty title="找不到符合的示意學生">換個姓名試試。</Empty>}{grant&&<GrantPackage close={()=>setGrant(false)}/>} {student&&<Modal title={`${student.name}的學習權益`} onClose={()=>setDetail(null)}><Flag>平台 {student.membership}</Flag><p className="x-copy">加入課程、存取權與一對一包是不同的資料，不在此直接升級或假裝付款。</p>{state.packages.filter(item=>item.studentId===student.id).map(item=><PackageSummary key={item.id} pack={item}/>)}{!state.packages.some(item=>item.studentId===student.id)&&<p>目前沒有一對一課程包。</p>}</Modal>}<Foot/></>;
}
function PackageSummary({pack}:{pack:StudentPackage}) {const {state}=usePrototype();const credit=balance(state,pack.id);return <section className="x-panel"><h3>{pack.snapshot.title}</h3><p>快照版本 {pack.offerVersion} · {modeName(pack.mode)} · 有效至 {pack.expiry}</p><div className="t-balance"><div><strong>{credit.available}</strong><small>可預約</small></div><div><strong>{credit.reserved}</strong><small>已預留</small></div><div><strong>{credit.consumed}</strong><small>已上課</small></div></div><p>來源：{pack.source}</p>{state.ledger.filter(item=>item.packageId===pack.id).map(item=><p className="micro" key={item.id}>{item.label} · {item.quantity} 堂</p>)}</section>}
function GrantPackage({close}:{close:()=>void}) {
  const {state,dispatch}=usePrototype();const {notify,confirm}=useWorkspaceActions();const [studentId,setStudent]=useState(state.students[0].id);const offers=state.offers.filter(item=>item.published&&(!item.published.targetStudentId||item.published.targetStudentId===studentId));const [offerId,setOffer]=useState(offers[0]?.id||"");const offer=offers.find(item=>item.id===offerId);const [mode,setMode]=useState<BookingMode>("flexible");const [expiry,setExpiry]=useState("2027-01-01");const [source,setSource]=useState<"manual-reissue"|"gift"|"offline-entitlement">("manual-reissue");const [reason,setReason]=useState("");
  return <Modal title="人工新增／補發課程包" onClose={close}><p className="x-copy">這是人工權益紀錄，必須留下原因。不能冒認付款，不改舊課程包。</p><Select label="受益學生" value={studentId} onChange={value=>{setStudent(value);setOffer("")}} options={state.students.map(item=>[item.id,item.name])}/><Select label="已核准課程包版本" value={offerId} onChange={setOffer} options={[["","請選擇"],...offers.map(item=>[item.id,`${item.published!.title} · 老師 ${item.teacherId} · v${item.version}`] as [string,string])]}/><Select label="這次的排課方式" value={mode} onChange={value=>setMode(value as BookingMode)} options={[["fixed","固定制"],["flexible","預約制"]]}/><Field label="權益有效至" type="date" value={expiry} onChange={setExpiry}/><Select label="人工來源（不代表已付款）" value={source} onChange={value=>setSource(value as typeof source)} options={[["manual-reissue","人工補發"],["gift","贈課"],["offline-entitlement","既有權益補登"]]}/><Area label="補發／補登原因" value={reason} onChange={setReason}/><Btn primary onClick={()=>{if(!offer||reason.trim().length<3)return notify("請選擇已核准課程包並填寫具體原因。");confirm("確認新增示意權益",<><h3>{state.students.find(item=>item.id===studentId)?.name} · {offer.published!.title}</h3><p>新增 {offer.published!.count} 堂 · {modeName(mode)} · 有效至 {expiry}</p><p>來源：{source}；原因：{reason}</p><p>不建立付款、預約或報酬。已購快照獨立保存。</p></>,()=>{const result=dispatch({type:"grantPackage",studentId,offerId,mode,expiry,source,reason,confirmed:true,requestId:`grant-${studentId}-${offerId}-${state.counter}`});notify(result.ok?"示意權益已新增，學生端會看到同一份課程包。":result.error!);if(result.ok)close();return result.ok})}}>預覽新增權益</Btn></Modal>;
}
export function AdminGuidance() {
  const {state,actor,dispatch}=usePrototype();const {notify,confirm}=useWorkspaceActions();const [selected,setSelected]=useState<string|null>(null);const [teacherId,setTeacher]=useState("t1");const [reason,setReason]=useState("");const list=visibleSubmissions(state,actor).filter(item=>item.kind==="pro");const submission=list.find(item=>item.id===selected);
  return <><Header eyebrow="PRO GUIDANCE / 讓每份練習有人接住" title="Pro 指導調度" sub="課程支援、學生資格與老師指派分開檢查；回覆不等於正式驗證。"/><Table headers={["學生／本次練習","課程／課節","狀態","指導老師","操作"]}>{list.map(item=><tr key={item.id}><td><strong>{state.students.find(student=>student.id===item.studentId)?.name}</strong><small>{item.title}</small></td><td>{state.courses.find(course=>course.id===item.courseId)?.published?.title}<small>{item.lessonId}</small></td><td><Flag active={item.status==="replied"}>{statusName(item.status)}</Flag></td><td>{state.teachers.find(teacher=>teacher.id===item.teacherId)?.draft.name||"尚未指派"}</td><td><Btn onClick={()=>{setSelected(item.id);setTeacher(item.teacherId||"t1");setReason("")}}>{item.status==="replied"?"查看回覆":"檢視並指派"}</Btn></td></tr>)}</Table>{!list.length&&<Empty title="目前沒有 Pro 練習提交">符合資格的學生在原生提交頁確認後，會出現在這裡。</Empty>}{submission&&<Modal title="這次的 Pro 練習" onClose={()=>setSelected(null)}><h3>{submission.title}</h3><p className="x-copy">{submission.question}</p><p>本地附件：{submission.mediaName}（沒有真實影片上傳）</p>{submission.status==="replied"?state.feedback.filter(item=>item.submissionId===submission.id).map(item=><section key={item.id}><h4>老師回饋</h4><p>{item.observation}</p><h4>下一次怎麼練</h4><p>{item.nextPractice}</p></section>):<><Select label="可指派的老師" value={teacherId} onChange={setTeacher} options={state.teachers.filter(item=>item.canReview).map(item=>[item.id,item.draft.name])}/><Area label="指派原因（必填）" value={reason} onChange={setReason}/><Btn primary onClick={()=>{if(reason.trim().length<3)return notify("請填寫指派原因。");confirm("確認本次服務指派",<><h3>{submission.title}</h3><p>指派給 {state.teachers.find(item=>item.id===teacherId)?.draft.name}</p><p>{reason}</p><p>只開放這份作業與課節背景，不建立永久私人課關係。</p></>,()=>{const result=dispatch({type:"assignSubmission",submissionId:submission.id,teacherId,reason});notify(result.ok?"已指派示意服務，老師的 Pro 平台指派會同步出現。":result.error!);if(result.ok)setSelected(null);return result.ok})}}>預覽服務指派</Btn></>}</Modal>}<Foot/></>;
}
export function OversightPage() {
  const {state,actor,dispatch}=usePrototype();const {notify}=useWorkspaceActions();const [studentId,setStudent]=useState(state.students[0]?.id||"");const [reason,setReason]=useState("");const [reply,setReply]=useState("");const access=state.oversightAccess.find(item=>item.actorId===actor.id&&item.studentId===studentId);const student=state.students.find(item=>item.id===studentId);
  return <><Header eyebrow="CONTROLLED OVERSIGHT / 必要時才打開" title="師生互動檢視" sub="先選定對象、填寫必要理由，才顯示指定互動。以平台身分協助，不冒用師生發言。"/><div className="x-editor"><section><Select label="本次需要協助的學生" value={studentId} onChange={value=>{dispatch({type:"closeOversight"});setStudent(value);setReason("");setReply("")}} options={state.students.map(item=>[item.id,item.name])}/><Area label="必要查看理由" value={reason} onChange={setReason}/><Btn primary onClick={()=>{const result=dispatch({type:"openOversight",studentId,reason});notify(result.ok?"已開啟指定學生的示意互動並記錄原因。":result.error!)}}>記錄理由並開啟互動</Btn>{access?<section className="section"><div className="section-head"><h2>{student?.name}的指定互動</h2><Btn onClick={()=>dispatch({type:"closeOversight"})}>重新遮蔽</Btn></div><p className="micro">已記錄理由：{access.reason}</p>{state.submissions.filter(item=>item.studentId===studentId).map(item=><article className="t-record" key={item.id}><Flag>學生示意提交</Flag><h3>{item.title}</h3><p>{item.question}</p>{state.feedback.filter(feedback=>feedback.submissionId===item.id).map(feedback=><div key={feedback.id}><h4>老師給學生的回饋</h4><p>{feedback.observation}</p><p>{feedback.nextPractice}</p></div>)}</article>)}{state.platformReplies.filter(item=>item.studentId===studentId).map(item=><article className="t-record" key={item.id}><Flag active>{item.authorLabel}</Flag><p>{item.body}</p></article>)}<Area label="以平台協助身分回覆（示意）" value={reply} onChange={setReply}/><Btn primary onClick={()=>{const result=dispatch({type:"platformReply",studentId,body:reply,reason:access.reason});notify(result.ok?"已記錄平台協助示意回覆。":result.error!);if(result.ok)setReply("")}}>留下平台協助回覆</Btn></section>:<div className="v4-locked"><Icon name="shield"/><h2>互動內容已遮蔽</h2><p>需要對象與具體理由。換對象或管理能力後必須重新開啟。</p></div>}</section><aside className="v4-guide"><h3>受控協助範圍</h3><p>僅顯示學生提交及給學生的回饋，不展開老師自己的私密備註。</p><p>所有查看與平台回覆都留操作紀錄；此頁沒有真實通知或正式資料。</p></aside></div><Foot/></>;
}
export function AuditPage() {
  const {state,actor,timeZone:zone}=usePrototype();const [selected,setSelected]=useState<string|null>(null);const entries=visibleAudit(state,actor);const detail=entries.find(item=>item.id===selected);
  return <><Header eyebrow="OPERATION HISTORY / 每一步都有依據" title="操作紀錄" sub="列出目前記憶體內的示意操作。重新整理會清除，並非正式稽核系統。"/>{entries.length?<Table headers={["時間","操作／對象","操作者","原因","檢視"]}>{entries.map(item=><tr key={item.id}><td>{dateTime(item.at,zone)}</td><td><strong>{item.action}</strong><small>{item.target}</small></td><td>{item.actor.role} · {item.actor.id}</td><td>{item.reason}</td><td><Btn onClick={()=>setSelected(item.id)}>查看影響</Btn></td></tr>)}</Table>:<Empty title="目前沒有可查看的操作">完成提案審核、示意預約或其他操作後，會依能力顯示紀錄。</Empty>}{detail&&<Modal title={detail.action} onClose={()=>setSelected(null)}><p>{detail.target} · {detail.reason}</p><h3>之前</h3><pre className="ux-audit-json">{JSON.stringify(detail.before,null,2)}</pre><h3>之後</h3><pre className="ux-audit-json">{JSON.stringify(detail.after,null,2)}</pre></Modal>}<Foot/></>;
}
export function AdminHome() {
  const {state,actor}=usePrototype();const pending=state.proposals.filter(item=>item.status==="review").length+state.offers.filter(item=>item.status==="review").length+state.teachers.filter(item=>item.status==="review").length;const unassigned=state.submissions.filter(item=>item.kind==="pro"&&!item.teacherId).length;
  return <><Header eyebrow="PLATFORM OPERATIONS / 看清全局，處理例外" title="管理員工作台" sub="把內容、老師與學生的需要接起來。重要操作都留下一筆紀錄。"/><div className="v4-band"><div><span className="eyebrow">{actor.capability==="owner"?"YOUR PLATFORM, YOUR VIEW":"OPERATIONS VIEW"}</span><h2>{actor.capability==="owner"?"收入與課務，現在分開看得清楚。":"把課務接好，財務留給獲授權的人。"}</h2><p>{actor.capability==="owner"?"平台財務包含收支、老師結算與報酬規則草稿；正式課程由管理員新增編輯。":"此視角可以管理內容、學生與預約；不顯示全站收款或老師報酬。"}</p></div><div className="v4-inline-actions">{actor.capability==="owner"&&<Go primary to="admin/finance">查看平台財務</Go>}<Go to="admin/courses">新增／編輯課程</Go></div></div><div className="x-admin-lead"><section className="x-admin-banner"><span className="eyebrow" style={{color:"#bfb99b"}}>THE ONE / OPERATIONS</span><h2>讓學習繼續，<br/>把卡住的事處理好。</h2><p>先處理需要協助的學生，再核准準備好的內容。</p><div className="x-actions"><Go primary to="admin/students">協助學生 <Icon name="arrow"/></Go><Go to="admin/articles">新增文章</Go></div></section><section className="x-panel"><h3>現在可以處理</h3>{[["review","book","課程與老師展示審核",pending?`${pending} 筆等待確認`:"老師送審後會出現在這裡"],["guidance","video","Pro 指導指派",unassigned?`${unassigned} 筆等待安排`:"支援的課程、合適的老師、受控指派"],["audit","shield","這次的操作紀錄",`${visibleAudit(state,actor).length} 筆本頁示意紀錄`]].map(([path,icon,title,sub])=><div className="x-queue-link" key={path}><span><Icon name={icon}/><span><b>{title}</b><small>{sub}</small></span></span><Go to={`admin/${path}`}>查看</Go></div>)}</section></div><section className="section"><div className="section-head"><div><h2>學生需要協助時</h2><p className="subtitle">先找到對的人與課程包，再決定怎麼處理。</p></div></div><div className="x-grid three">{[["bookings","代學生預約","選擇學生、老師、課程包與可用時段。預約只預留堂數，不代表已上課。"],["students","新增／補發課程包","記下補登、贈課或補發原因，不把人工授予變成假付款。"],["oversight","檢視師生互動","必要時開啟指定對話。必須填原因，不冒充老師或學生發言。"]].map(([path,title,sub])=><div className="x-panel" key={path}><h3>{title}</h3><p>{sub}</p><div className="x-actions"><Go to={`admin/${path}`}>開啟{title}</Go></div></div>)}</div></section><Foot/></>;
}
export function OperationDenied() {const {actor}=usePrototype();return <Empty title="目前能力無法開啟這個操作">{canOperate(actor)?"請使用管理員入口。":"財務人員只開放財務作業；內容、學生與預約需要營運能力。"}<Go to="admin/finance">前往平台財務</Go></Empty>}
