"use client";
import Link from "@/components/platform-experience/link";
import { createContext, useContext, useEffect, useId, useRef, type ReactNode } from "react";
import { usePrototype } from "@/modules/ux-prototype/store";

export const base = "/ux-prototype";
export const money = (amount: number | null) => amount === null ? "待核對／未設定" : `NT$ ${amount.toLocaleString("en-US")}`;
export const dateTime = (value: string, timeZone = "Asia/Taipei") => new Intl.DateTimeFormat("zh-TW",{timeZone,month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));
export const modeName = (mode: string) => mode === "fixed" ? "固定制" : mode === "flexible" ? "預約制" : "固定制／預約制";
export const statusName = (status: string) => ({draft:"草稿",review:"待審核",published:"已發布",changes:"請補充說明",imported:"平台已匯入草稿",superseded:"已被修訂版取代",reserved:"已預約，尚未上課",cancelled:"已取消",completed:"已上課",submitted:"等待指派",assigned:"待回覆",replied:"已回覆",ready:"已確認待撥",paid:"已記錄撥款",unconfigured:"規則尚未核准",approved:"已覆核，尚未撥款",prepared:"待負責人覆核"}[status]??status);
export const WorkspaceActions = createContext<{notify:(text:string)=>void;confirm:(title:string,body:ReactNode,action:()=>boolean)=>void}>({notify:()=>{},confirm:()=>{}});
export const useWorkspaceActions=()=>useContext(WorkspaceActions);
export function Icon({name}:{name:string}){const paths:Record<string,ReactNode>={home:<><path d="m3 10 9-7 9 7v11h-6v-7H9v7H3z"/></>,book:<><path d="M3 3h7l2 2 2-2h7v17h-7l-2 1-2-1H3zM12 5v16"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18M7 15h3m4 0h3M7 18h3"/></>,people:<><circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4m2-11a3 3 0 0 0 0-6m1 10a5 5 0 0 1 3 4v3"/></>,chat:<><path d="M21 11a9 9 0 0 1-9 9H4l-2 2 1-7a9 9 0 1 1 18-4Z"/><path d="M7 9h10M7 13h7"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 8h18M16 12h5v5h-5zM6 5l11-3"/></>,edit:<><path d="m4 15 11-11 5 5L9 20H4zM13 6l5 5M3 22h18"/></>,file:<><path d="M5 2h9l5 5v15H5zM14 2v6h5M8 12h8M8 16h8"/></>,shield:<><path d="m12 2 9 4-2 11-7 5-7-5L3 6zM8 11l3 3 5-6"/></>,search:<><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></>,moon:<><path d="M19 16A9 9 0 0 1 8 4a9 9 0 1 0 11 12Z"/></>,settings:<><path d="m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z"/><circle cx="12" cy="12" r="3"/></>,video:<><rect x="2" y="5" width="14" height="14" rx="2"/><path d="m16 9 6-3v12l-6-3"/></>,arrow:<path d="m9 5 7 7-7 7"/>,menu:<path d="M3 6h18M3 12h18M3 18h18"/>,close:<path d="m5 5 14 14M5 19 19 5"/>,play:<path d="m8 4 12 8-12 8z"/>};return <svg aria-hidden="true" viewBox="0 0 24 24">{paths[name]??paths.file}</svg>}
export function Btn({children,onClick,primary=false,disabled=false}:{children:ReactNode;onClick?:()=>void;primary?:boolean;disabled?:boolean}){return <button type="button" className={`btn ${primary?"primary":"secondary"}`} onClick={onClick} disabled={disabled}>{children}</button>}
export function Go({children,to,primary=false}:{children:ReactNode;to:string;primary?:boolean}){return <Link className={`btn ${primary?"primary":"secondary"}`} href={`${base}/${to}`}>{children}</Link>}
export function Header({eyebrow,title,sub,tools}:{eyebrow:string;title:string;sub:string;tools?:ReactNode}){const {actor,theme,setTheme}=usePrototype();return <header className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="subtitle">{sub}</p></div><div className="header-tools">{tools}<Link className="icon-button" aria-label="搜尋學生" href={`${base}/${actor.role}/students`}><Icon name="search"/></Link><button className="icon-button" aria-label="切換深淺外觀" onClick={()=>setTheme(theme==="dark"?"light":"dark")}><Icon name="moon"/></button></div></header>}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="v4-box"><h2>{title}</h2><p style={{marginTop:12}}>{children}</p></div>}
export function Flag({children,active=false}:{children:ReactNode;active?:boolean}){return <span className={`mini-chip ${active?"active":""}`}>{children}</span>}
export function Field({label,value,onChange,type="text",disabled=false,placeholder}:{label:string;value:string|number;onChange?:(value:string)=>void;type?:string;disabled?:boolean;placeholder?:string}){const id=useId();return <div className="x-field"><label className="x-label" htmlFor={id}>{label}</label><input id={id} type={type} value={value} onChange={e=>onChange?.(e.target.value)} readOnly={!onChange} disabled={disabled} placeholder={placeholder}/></div>}
export function Area({label,value,onChange,disabled=false}:{label:string;value:string;onChange?:(value:string)=>void;disabled?:boolean}){const id=useId();return <div className="x-field"><label className="x-label" htmlFor={id}>{label}</label><textarea id={id} value={value} onChange={e=>onChange?.(e.target.value)} readOnly={!onChange} disabled={disabled}/></div>}
export function Select({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;options:[string,string][];disabled?:boolean}){const id=useId();return <div className="x-field"><label className="x-label" htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}>{options.map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></div>}
export function Check({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <label className="x-check"><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
export function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="v4-scroll" role="region" aria-label="可左右捲動的資料表" tabIndex={0}><table className="v4-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export function Tabs({items,value,onChange}:{items:[string,string][];value:string;onChange:(value:string)=>void}){return <div className="tabs" role="tablist">{items.map(([id,label])=><button role="tab" aria-selected={value===id} className={`tab ${value===id?"active":""}`} key={id} onClick={()=>onChange(id)}>{label}</button>)}</div>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);const id=useId();useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();previous?.focus()}},[]);return <dialog className={wide?"x-wide-dialog":undefined} ref={ref} aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose()}}><div className="row between"><h2 id={id}>{title}</h2><button aria-label="關閉對話框" onClick={onClose}><Icon name="close"/></button></div>{children}</dialog>}
export function Foot(){return <p className="footnote">本機互動雛形 · 金額、合約、人物與課程資料皆為示意。重整即重設；只有外觀偏好會保留。沒有真實付款、登入、通知或資料庫連線。</p>}
