"use client";

import Link from "@/components/platform-experience/link";
import { useState } from "react";
import { usePrototype } from "@/modules/ux-prototype/store";
import { balance, visibleFeedback, visibleSubmissions, visibleTeachingDrafts, type Booking, type Student, type Submission } from "@/modules/ux-prototype/model";
import { Area, Btn, Empty, Field, Flag, Foot, Go, Header, Icon, Select, Table, Tabs, base, dateTime, modeName, statusName, useWorkspaceActions } from "./shared";

function Avatar({student,large=false}:{student:Student;large?:boolean}) {return <span className={`t-avatar ${large?"large":""}`}>{student.initial}</span>}
function QueueCard({submission}:{submission:Submission}) {
  const {state}=usePrototype(); const student=state.students.find(item=>item.id===submission.studentId)!;
  return <Link className="t-queue-row" href={`${base}/teacher/reviews/${submission.id}`}><div className="row"><Avatar student={student}/><div className="grow"><strong>{student.name}</strong><span className="micro">{submission.kind==="private"?"私人課作業":"平台指派批改"}</span></div><Flag active={submission.status!=="replied"}>{submission.status==="replied"?"已回覆":"待回覆"}</Flag></div><h3>{submission.title}</h3><div className="row between"><span className="micro">練習影片 {submission.duration} · 內容示意</span><Icon name="arrow"/></div></Link>;
}
function BookingRow({booking}:{booking:Booking}) {
  const {state,timeZone:zone}=usePrototype();const student=state.students.find(item=>item.id===booking.studentId)!;
  const time=(iso:string)=>new Intl.DateTimeFormat("zh-TW",{timeZone:zone,hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(iso));
  return <div className="t-agenda-row"><div className="t-time">{time(booking.start)}<small>{time(booking.end)}</small></div><Avatar student={student}/><div className="grow"><strong>{student.name} <Flag>{modeName(booking.mode)}</Flag></strong><p>{student.focus} · 線上 · 50 分鐘</p></div><Go to={`teacher/lessons/${booking.id}`}>課前準備 <Icon name="arrow"/></Go></div>;
}
function StudentCard({student}:{student:Student}) {
  const {state,actor}=usePrototype();const own=student.teacherId===actor.id&&student.relation==="private";
  const pack=state.packages.find(item=>item.studentId===student.id&&item.teacherId===actor.id);const progress=student.progress[0];
  return <article className="t-student-card"><div className="row"><Avatar student={student}/><div><h3>{student.name}</h3><p className="micro">{own?`私人課學生 · ${modeName(pack?.mode||"flexible")}`:"平台指派批改"}</p></div></div><div className="t-student-focus">{student.focus}</div><p className="small muted">{!own?"只顯示本次指派所需資訊":student.joinedCourseIds.length?`吉他學習地圖 · Stage ${progress?.stage||2}`:"私人課學習 · 尚未加入系統課程"}</p><div className="row between t-card-end"><span className="micro">{!own?"不是永久私人課關係":student.joinedCourseIds.length?`${progress?.selfCompleted.length||0} / 6 課 · 學生自報完成`:"不建立假課程進度"}</span><Link className="text-button" href={`${base}/teacher/students/${student.id}`}>打開 <Icon name="arrow"/></Link></div></article>;
}
function useTeachingScope() {
  const {state,actor}=usePrototype();const submissions=visibleSubmissions(state,actor);
  return {submissions,students:state.students.filter(student=>(student.relation==="private"&&student.teacherId===actor.id)||submissions.some(item=>item.studentId===student.id)),bookings:state.bookings.filter(item=>item.teacherId===actor.id&&item.status==="reserved").sort((a,b)=>a.start.localeCompare(b.start))};
}
export function TeacherToday() {
  const {state,timeZone:zone}=usePrototype();const displayZone=zone==="Asia/Taipei"?"台北時間 UTC+8":zone==="Asia/Tokyo"?"東京時間 UTC+9":"洛杉磯時間";const {students,bookings,submissions}=useTeachingScope();const next=bookings.find(item=>item.start>state.clock);const student=students.find(item=>item.id===next?.studentId);const pending=submissions.filter(item=>item.status!=="replied");
  return <><Header eyebrow="TEACHER WORKSPACE / 老師空間" title="今日教學" sub="先看下一堂，再把需要的回饋送到學生手上。" tools={<Flag>示範課次 · 9/9</Flag>}/><div className="today-top t-today-top"><section className="continue-card t-next"><div className="eyebrow"><span className="accent">●</span> 下一堂，一起練好這一步</div>{next&&student?<><div className="t-hero-student"><Avatar student={student} large/><div><h2>先陪{student.name}，<br/>穩定這一拍。</h2><Flag>{modeName(next.mode)}一對一 · 線上課</Flag></div></div><div className="current-line">{dateTime(next.start,zone)}–{new Intl.DateTimeFormat("zh-TW",{timeZone:zone,hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(next.end))} · {displayZone}</div><div className="current-lesson">{student.focus}</div><p className="t-hero-note">上次卡在切音後的下一拍。<br/>今天先慢速連起來，再放回音樂裡。</p><div className="continue-actions"><Go primary to={`teacher/lessons/${next.id}`}><Icon name="file"/>課前準備</Go><Link className="text-button" href={`${base}/teacher/students/${student.id}`}>看看{student.name}的學習 <Icon name="arrow"/></Link></div></>:<><h2>今天沒有<br/>已安排的課。</h2><p className="t-hero-note">可以整理下次的練習，或查看本週的可預約時段。</p><Go to="teacher/schedule" primary>看看課表</Go></>}</section><section className="t-queue"><div className="section-head"><div><h2>等你回覆</h2><p className="subtitle">私人課作業與平台批改，分清楚來源。</p></div><Link className="text-button" href={`${base}/teacher/reviews`}>全部 <Icon name="arrow"/></Link></div>{pending.length?pending.slice(0,2).map(item=><QueueCard key={item.id} submission={item}/>):<Empty title="目前沒有待回覆的作業">有新的指派時，再回到這裡。</Empty>}</section></div><section className="section"><div className="section-head"><div><h2>今天的教學安排</h2><p className="subtitle">{displayZone} · 日期為示意，不連接真實行事曆</p></div><Go to="teacher/schedule">完整課表</Go></div><div className="t-agenda">{bookings.length?bookings.map(item=><BookingRow key={item.id} booking={item}/>):<p className="t-empty-line">沒有已確認預約。</p>}</div></section><section className="section"><div className="section-head"><div><h2>你正在陪伴的學生</h2><p className="subtitle">私人課的持續陪伴，與本次平台指派分開呈現。</p></div><Go to="teacher/students">我的學生</Go></div><div className="t-student-grid">{students.map(item=><StudentCard key={item.id} student={item}/>)}</div></section><section className="section v4-grid"><div className="v4-box"><h3>我的收入</h3><p>每一筆教學服務與內容報酬，都能對照狀態與來源。</p><div className="v4-inline-actions"><Go primary to="teacher/earnings">查看自己的報酬</Go></div></div><div className="v4-box"><h3>學生請你安排下一堂？</h3><p>先確認時段，替自己的預約制學生完成線上代約。</p><div className="v4-inline-actions"><Go to="teacher/book-for-student">幫學生預約</Go></div></div></section><Foot/></>;
}
export function TeacherStudents({id}:{id?:string}) {
  const {students,submissions,bookings}=useTeachingScope();const {state,actor,dispatch}=usePrototype();const {notify}=useWorkspaceActions();const [query,setQuery]=useState("");const student=students.find(item=>item.id===id);const [note,setNote]=useState(state.privateNotes.find(item=>item.teacherId===actor.id&&item.studentId===id)?.text||"");
  if(id&&!student)return <Empty title="無法查看這位學生">只開放自己私人課關係或本次平台指派所需的背景。<Go to="teacher/students">回我的學生</Go></Empty>;
  if(!student)return <><Header eyebrow="YOUR STUDENTS / 教學關係" title="我的學生" sub="只放你有教學關係，或本次被指派服務的學生。"/><div className="t-filter"><div className="t-search"><Icon name="search"/><input aria-label="搜尋學生或練習內容" placeholder="搜尋學生或正在練習的內容" value={query} onChange={event=>setQuery(event.target.value)}/></div><Flag>示意名單 · 不是全平台學生</Flag></div><div className="t-student-grid">{students.filter(item=>`${item.name} ${item.focus}`.includes(query)).map(item=><StudentCard key={item.id} student={item}/>)}</div>{!students.some(item=>`${item.name} ${item.focus}`.includes(query))&&<Empty title="沒有符合條件的學生">試試其他姓名或練習內容。</Empty>}<aside className="t-boundary"><Icon name="shield"/><p>教學關係或被指派批改，不代表能查看全平台學生、其他老師的備註，或更改會員權限。</p></aside><Foot/></>;
  const own=student.teacherId===actor.id&&student.relation==="private";const pack=state.packages.find(item=>item.studentId===student.id&&item.teacherId===actor.id);const credit=pack?balance(state,pack.id):null;
  return <><Header eyebrow="STUDENT CONTEXT / 了解現在這一步" title={`${student.name}的學習`} sub={own?`私人課學生 · ${modeName(pack?.mode||"flexible")}一對一`:"平台指派批改"} tools={<Go to="teacher/students">我的學生</Go>}/>{own?<><div className="t-detail-top"><section><div className="row"><Avatar student={student} large/><div><h2>{student.focus}</h2><p className="subtitle">依照這次的練習狀況，安排下一小步。</p></div></div><div className="section-head" style={{marginTop:32}}><h3>目前的學習路線</h3></div>{student.joinedCourseIds.length?<><div className="t-stage-journey">{["把一首歌彈完","讓伴奏有變化","理解正在彈什麼"].map((title,index)=><div className={`t-stage ${index===1?"active":""}`} key={title}><span className="t-stage-no">0{index+1}</span><div><span className="eyebrow">STAGE {index+1}</span><h3>{title}</h3><p className="micro">{index===1?"目前階段":index===0?"先前階段 · 未展示完成資料":"後續方向 · 不等於鎖定"}</p></div></div>)}</div><p className="micro">只展示三個代表性階段；{student.progress[0]?.selfCompleted.length||0} / 6 課為學生自報，老師驗證尚未進行。</p></>:<div className="t-no-map"><h3>私人課照常上，不需要先加入錄播課。</h3><p>尚未加入吉他學習地圖，不顯示假課程百分比或階段完成狀態。</p></div>}</section><aside className="t-package"><span className="eyebrow">PRIVATE LESSON / 一對一堂數</span><h3>{modeName(pack?.mode||"flexible")}私人課</h3><p>預約方式與會員方案分開。</p>{credit&&<div className="t-balance"><div><strong>{credit.available}</strong><small>可預約</small></div><div><strong>{credit.reserved}</strong><small>已預留</small></div><div><strong>{credit.consumed}</strong><small>已上課</small></div></div>}<p className="micro">已預留不等於已上課。筆記與回饋不扣堂數。</p></aside></div><section className="section"><div className="section-head"><h2>先記住這一件事</h2></div><div className="t-two"><div className="t-reading"><Flag active>學生可見的練習方向 · 範例</Flag><h3 style={{marginTop:18}}>{student.focus}</h3><p>{student.note}</p>{bookings.find(item=>item.studentId===student.id)&&<Go to={`teacher/lessons/${bookings.find(item=>item.studentId===student.id)!.id}`}>寫本堂紀錄</Go>}</div><div className="t-note-editor"><Area label="只留給自己的備註" value={note} onChange={setNote}/><p className="micro">本機記憶體示意，不會混入給學生的內容。</p><Btn onClick={()=>{const result=dispatch({type:"savePrivateNote",studentId:student.id,text:note});notify(result.ok?"已儲存僅老師可見的示意備註。":result.error!)}}>儲存示意備註</Btn></div></div></section>{pack?.mode==="flexible"&&<div className="v4-inline-actions"><Go primary to={`teacher/book-for-student?student=${student.id}`}>幫這位學生預約線上課</Go></div>}</>:<><div className="t-boundary"><Icon name="shield"/><p>本次指派只開放這筆作業與課節背景，不開放私人課紀錄、課程包或教師私密備註。</p></div><div className="t-reading"><span className="eyebrow">本次課節背景</span><h2>吉他學習地圖 · Stage 2</h2><p>右手節奏與切音 / 練習不同的伴奏表情</p>{submissions.filter(item=>item.studentId===student.id).map(item=><QueueCard key={item.id} submission={item}/>)}</div></>}<Foot/></>;
}
export function TeacherReviews({id}:{id?:string}) {
  const {state,actor,dispatch}=usePrototype();const {notify,confirm}=useWorkspaceActions();const [filter,setFilter]=useState("pending");const submissions=visibleSubmissions(state,actor);const submission=submissions.find(item=>item.id===id);const sent=visibleFeedback(state,actor).find(item=>item.submissionId===id);const savedDraft=visibleTeachingDrafts(state,actor).find(item=>item.kind==="review"&&item.targetId===id);const [observation,setObservation]=useState(sent?.observation??savedDraft?.observation??"");const [practice,setPractice]=useState(sent?.nextPractice??savedDraft?.nextPractice??"");const [draftSaved,setDraftSaved]=useState(Boolean(savedDraft));
  if(id&&!submission)return <Empty title="這份作業不在你的教學範圍內">請從已指派的作業清單開啟。<Go to="teacher/reviews">回作業列表</Go></Empty>;
  if(!submission){const list=submissions.filter(item=>filter==="sent"?item.status==="replied":filter==="private"?item.kind==="private":filter==="platform"?item.kind==="pro":item.status!=="replied");return <><Header eyebrow="REVIEW & FEEDBACK / 一次陪好一個問題" title="作業與回饋" sub="看見學生的練習，再留下他做得到的下一步。"/><Tabs items={[["pending","待回覆"],["private","私人課作業"],["platform","Pro 平台指派"],["sent","已回覆"]]} value={filter} onChange={setFilter}/><div className="t-review-grid">{list.length?list.map(item=><QueueCard key={item.id} submission={item}/>):<Empty title="這裡目前沒有作業">新的作業或指派會放在這裡。</Empty>}</div><aside className="x-note"><Icon name="shield"/><p>私人課作業與 Pro 指導分開。老師只看得到有教學關係或被指派的內容；回覆不會直接變成正式驗證或證書。</p></aside><Foot/></>}
  const student=state.students.find(item=>item.id===submission.studentId)!;
  return <><Header eyebrow={`REVIEW WORKSPACE / ${submission.kind==="private"?"私人課作業":"平台指派批改"}`} title={`${student.name}的練習`} sub={submission.title} tools={<Go to="teacher/reviews">回到作業列表</Go>}/><div className="t-review-work"><div><div className="t-evidence" role="img" aria-label="學生練習影片佔位，沒有真實影片"><Flag>練習影片 · {submission.duration}</Flag><div className="t-evidence-middle"><Icon name="play"/><h2>先聽見學生的練習。</h2><p>目前為影片版位，未提供真實影音。</p></div><div className="row between"><span>第 1 次提交 · 示意</span><span>00:00 / {submission.duration}</span></div></div><section className="t-reading" style={{marginTop:22}}><span className="eyebrow">學生想問的問題</span><p>{submission.question}</p><div className="hairline" style={{marginTop:20}}/><p className="small muted">課節：吉他學習地圖 / Stage 2 / {submission.lessonId}</p><p className="micro">{submission.kind==="private"?"私人課關係內的作業":"本次平台指派的作業"}。此處沒有其他教師的筆記或服務資料。</p></section></div><section className="t-feedback-form"><div className="row between"><h2>{sent?"這次的回饋":"給一個清楚的下一步"}</h2><Flag active={!sent}>{sent?"本頁已回覆":"待回覆"}</Flag></div><p className="subtitle">先聽切音後的第一拍，再看看右手是否持續擺動。</p><label htmlFor="feedback-text">給學生的回饋</label><textarea id="feedback-text" maxLength={2000} readOnly={Boolean(sent)} value={sent?.observation??observation} onChange={e=>{setObservation(e.target.value);setDraftSaved(false)}} placeholder="例如：右手在切音後先不要停住，保持擺動，再輕輕接回下一拍。"/><label htmlFor="practice-text">下一次怎麼練</label><textarea id="practice-text" className="short" maxLength={1500} readOnly={Boolean(sent)} value={sent?.nextPractice??practice} onChange={e=>{setPractice(e.target.value);setDraftSaved(false)}} placeholder="例如：先用空弦慢速練 4 小節，錄下切音後的第一拍。"/><p className="micro">這兩欄給學生看；僅教師的備註另存，不會帶入這裡。</p><div className="t-form-actions">{sent?<Go to="teacher/records">查看本頁回饋紀錄</Go>:<><Btn onClick={()=>{const result=dispatch({type:"saveTeachingDraft",kind:"review",targetId:submission.id,observation,nextPractice:practice});setDraftSaved(result.ok);notify(result.ok?"草稿已保存，可離開後回到這份作業繼續；尚未送給學生。":result.error!)}}>{draftSaved?"本頁草稿已保留":"儲存草稿"}</Btn><Btn primary onClick={()=>{if(!observation.trim()||!practice.trim())return notify("請填寫給學生的回饋與下一次怎麼練。");confirm("確認給學生的示意回饋",<><h3>{student.name} · {submission.title}</h3><p>{observation}</p><h4>下一次怎麼練</h4><p>{practice}</p><p>不扣額度、不給驗證、不發送通知。</p></>,()=>{const result=dispatch({type:"reply",submissionId:submission.id,observation,nextPractice:practice,privateNote:""});notify(result.ok?"示意回饋已送出，學生端可見。":result.error!);return result.ok})}}>預覽並送出示意 <Icon name="arrow"/></Btn></>}</div><p className="micro t-safe-copy">回饋不等於驗證通過。此操作不發送通知、不扣額度、不改學習進度。</p></section></div><Foot/></>;
}
export function TeacherLesson({id}:{id:string}) {
  const {state,actor,dispatch,timeZone:zone}=usePrototype();const displayZone=zone==="Asia/Taipei"?"台北時間 UTC+8":zone==="Asia/Tokyo"?"東京時間 UTC+9":"洛杉磯時間";const {notify}=useWorkspaceActions();const booking=state.bookings.find(item=>item.id===id&&item.teacherId===actor.id);const record=state.lessonRecords.find(item=>item.bookingId===id&&item.teacherId===actor.id);const savedDraft=visibleTeachingDrafts(state,actor).find(item=>item.kind==="lesson"&&item.targetId===id);const [note,setNote]=useState(savedDraft?.observation??record?.publicNote??"");const [practice,setPractice]=useState(savedDraft?.nextPractice??record?.practice??"");
  if(!booking)return <Empty title="找不到可查看的課前資訊">此預約不屬於你。<Go to="teacher/schedule">回課表</Go></Empty>;
  const student=state.students.find(item=>item.id===booking.studentId)!;
  return <><Header eyebrow={`LESSON NOTES / ${modeName(booking.mode)}一對一`} title={`${student.name}的課前準備`} sub="上次練了什麼、今天怎麼教，以及課後留下哪一步。" tools={<Go to="teacher">今日教學</Go>}/><div className="t-two"><section><div className="t-reading"><Flag active>{statusName(booking.status)} · 範例</Flag><h2 style={{marginTop:18}}>{student.focus}</h2><p>{dateTime(booking.start,zone)} · {displayZone}</p><p>線上 · {modeName(booking.mode)} · 50 分鐘</p><Btn onClick={()=>notify("線上教室連結尚未接線；沒有真實會議網址。")}>查看上課入口</Btn></div><section className="section"><h3>上次留下的重點</h3><p className="subtitle">{student.note}</p><div className="t-plan-steps">{["先聽學生彈一小段","拆開這次最容易卡的地方","留下下次可以照做的練習"].map((item,index)=><div key={item}><b>0{index+1}</b><span>{item}<small>一起慢速練，再確認學生能自己做。</small></span></div>)}</div><Go to={`teacher/students/${student.id}`}>查看學生學習背景</Go></section></section><section className="t-feedback-form"><h2>本堂教學紀錄</h2><p className="subtitle">回饋與練習分開寫，讓學生回家看得懂。</p><Area label="本堂重點 · 學生可見" value={note} onChange={setNote}/><Area label="課後練習 · 學生可見" value={practice} onChange={setPractice}/><div className="t-form-actions"><Btn onClick={()=>{const result=dispatch({type:"saveTeachingDraft",kind:"lesson",targetId:booking.id,observation:note,nextPractice:practice});notify(result.ok?"教學草稿已保存，可稍後返回；尚未顯示給學生。":result.error!)}}>存成草稿</Btn><Btn primary onClick={()=>{if(!note.trim()||!practice.trim())return notify("請填寫本堂重點與課後練習。");const result=dispatch({type:"saveLessonRecord",bookingId:booking.id,publicNote:note,privateNote:record?.privateNote||"",practice});notify(result.ok?"已保存教學紀錄，沒有扣堂或完成預約。":result.error!)}}>保存示意紀錄</Btn></div><p className="micro t-safe-copy">儲存教學紀錄不會把預約標成已上課，也不扣堂數。教師私人備註在學生頁另存。</p></section></div><Foot/></>;
}
export function TeacherRecords() {
  const {state,actor}=usePrototype();const [tab,setTab]=useState("shared");const feedback=visibleFeedback(state,actor);const records=state.lessonRecords.filter(item=>item.teacherId===actor.id);const notes=state.privateNotes.filter(item=>item.teacherId===actor.id);
  return <><Header eyebrow="TEACHING RECORDS / 接得上每一次教學" title="教學紀錄" sub="給學生的回饋與自己的備註，分開保留。"/><Tabs items={[["shared","給學生的回饋"],["private","自己的備註"]]} value={tab} onChange={setTab}/>{tab==="shared"?<>{feedback.map(item=><article className="t-record" key={item.id}><h3>{state.students.find(student=>student.id===item.studentId)?.name} · 作業回饋</h3><h4>給學生的回饋</h4><p className="t-prewrap">{item.observation}</p><h4>下一步怎麼練</h4><p>{item.nextPractice}</p></article>)}{records.map(item=><article className="t-record" key={item.id}><h3>{state.students.find(student=>student.id===item.studentId)?.name} · 教學紀錄</h3><h4>本堂重點</h4><p>{item.publicNote}</p><h4>課後練習</h4><p>{item.practice}</p></article>)}{!feedback.length&&!records.length&&<Empty title="先完成一份回饋，讓下一次學習有依據。"><Go to="teacher/reviews">開始回覆</Go></Empty>}</>:<>{notes.map(item=><article className="t-record" key={item.id}><Flag>僅教師備註 · 示意</Flag><h3>{state.students.find(student=>student.id===item.studentId)?.name}</h3><p className="t-prewrap">{item.text}</p></article>)}{!notes.length&&<Empty title="尚未留下自己的備註">到自己的私人課學生頁即可試寫。</Empty>}</>}<Foot/></>;
}
export function TeacherSchedule() {
  const {state,timeZone:zone,setTimeZone:setZone}=usePrototype();const {bookings}=useTeachingScope();const fmt=(iso:string)=>new Intl.DateTimeFormat("zh-TW",{timeZone:zone,month:"numeric",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(iso));
  return <><Header eyebrow="YOUR ONLINE SCHEDULE / 接好每一堂的起點" title="我的課表" sub="目前只提供線上課程。固定制優先時段與預約制仍分開。"/><section className="v4-band"><div><h2>線上見，照著自己的步伐學。</h2><p>日期為情境示意，示範課次不是你的真實行事曆。</p></div><Flag active>ONLINE ONLY</Flag></section><div className="v4-toolbar"><Go primary to="teacher/book-for-student">幫預約制學生預約</Go><Select label="課表顯示時區" value={zone} onChange={setZone} options={[["Asia/Taipei","台北時間 UTC+8"],["Asia/Tokyo","東京時間 UTC+9"],["America/Los_Angeles","洛杉磯時間"]]}/></div>{bookings.length?<Table headers={["學生／課題","日期與時間","排課模式","狀態",""]}>{bookings.map(item=><tr key={item.id}><td><strong>{state.students.find(student=>student.id===item.studentId)?.name}</strong><small>{state.students.find(student=>student.id===item.studentId)?.focus}</small></td><td>{fmt(item.start)}<small>{zone}</small></td><td>{modeName(item.mode)}<small>線上教室</small></td><td><Flag>{statusName(item.status)}</Flag><small>{item.createdBy==="fixture"?"既有示意預約":"已記錄同意依據"}</small></td><td><Go to={`teacher/lessons/${item.id}`}>查看課前資訊</Go></td></tr>)}</Table>:<Empty title="目前沒有已確認預約">公開可約時段與已預約課次是不同資料。</Empty>}<p className="footnote">新增可用時段與預約是不同操作。本輪依最新流程只提供已公開時段的代約，不新增實體據點或自行授予固定時段。</p><Foot/></>;
}
export function WorkspaceSettings() {
  const {theme,setTheme,actor,setActor,timeZone,setTimeZone}=usePrototype();
  return <><Header eyebrow="MAKE IT YOURS / 你的使用習慣" title="設定" sub="把工作空間，調成你舒服的樣子。"/><div className="settings-layout"><section className="setting-block"><h2>外觀</h2><p className="subtitle">白色、黑色，或跟著你的裝置。公開頁維持白色，已核准播放器維持深色。</p><div className="theme-choices">{(["light","dark","system"] as const).map(item=><button className={`theme-option ${theme===item?"selected":""}`} aria-pressed={theme===item} key={item} onClick={()=>setTheme(item)}><span className={`theme-swatch ${item}`}/><strong>{item==="light"?"白色":item==="dark"?"黑色":"跟隨系統"}</strong></button>)}</div></section><section className="setting-block"><h2>上課時間顯示</h2><Select label="工作台顯示時區" value={timeZone} onChange={setTimeZone} options={[["Asia/Taipei","台北時間 UTC+8"],["Asia/Tokyo","東京時間 UTC+9"],["America/Los_Angeles","洛杉磯時間"]]}/><p className="micro">同一筆 UTC 預約轉換顯示，時區偏好跨頁保留。</p></section><section className="setting-block"><h2>本機角色範圍檢查</h2>{actor.role==="teacher"?<Select label="示意老師帳號" value={actor.id} onChange={id=>setActor({role:"teacher",id})} options={[["t1","The One 老師"],["t2","合作老師 B（無教學關係）"]]}/>:<Field label="管理員能力由頁面上方切換" value={actor.capability||"owner"}/>}<p className="micro">這是本地 fixture 情境，不能當作正式授權機制。</p></section></div><Foot/></>;
}
