"use client";
import { useState } from "react";
import { useRouter } from "@/components/platform-experience/link";
import Image from "next/image";
import { usePrototype } from "@/modules/ux-prototype/store";
import { policiesAccepted, type CourseContent, type OfferContent, type PackageOffer, type TeacherProfile } from "@/modules/ux-prototype/model";
import { Area, Btn, Check, Empty, Field, Flag, Foot, Go, Header, Modal, Select, Tabs, base, money, modeName, statusName, useWorkspaceActions } from "./shared";

export function TeacherCourses({proposalId}:{proposalId?:string}) {
  const {state,actor,dispatch}=usePrototype();const {notify}=useWorkspaceActions();const router=useRouter();const [tab,setTab]=useState("recorded");const [offerId,setOfferId]=useState<string|null>(null);
  function create(baseCourseId?:string){const result=dispatch({type:"createProposal",baseCourseId});if(result.ok)router.push(`${base}/teacher/proposals/${result.id}`);else notify(result.error!)}
  if(proposalId)return <ProposalEditor key={proposalId} id={proposalId}/>;
  const proposals=state.proposals.filter(item=>item.teacherId===actor.id),courses=state.courses.filter(item=>item.teacherId===actor.id&&item.published);
  return <><Header eyebrow="MY COURSES / 你的教學提案，由平台把關" title="我的課程" sub="老師提出教學內容與價格建議；正式課程的新增、編輯及發布由平台處理。"/><Tabs items={[["recorded","錄播課程與提案"],["private","一對一課程包"]]} value={tab} onChange={setTab}/>{tab==="recorded"?<><div className="v4-band"><div><h2>有新的教學想法？先提案。</h2><p>不用冒險改到已上架課程。平台會先看目標、課綱、素材權利與服務方式。</p></div><Btn primary onClick={()=>create()}>＋ 新增課程提案</Btn></div><section><div className="section-head"><h2>我的提案</h2><Go to="teacher/policies">查看提案守則</Go></div>{proposals.length?<div className="v4-list">{proposals.map(item=><article key={item.id}><Flag active={item.status!=="draft"}>{statusName(item.status)}</Flag><div className="grow"><h3>{item.content.title||"尚未命名的課程提案"}</h3><p>{item.baseCourseId?"既有課程內容更新":"新課程建議"} · 提案版本 {item.revision}{item.reviewNote&&<><br/>平台回覆：{item.reviewNote}</>}</p></div><Go to={`teacher/proposals/${item.id}`}>{["draft","changes"].includes(item.status)?"繼續填寫":"查看提案"}</Go></article>)}</div>:<Empty title="從一個清楚的學習成果開始">新增提案不會直接讓訪客看到這門課。</Empty>}</section><section className="section"><div className="section-head"><h2>參與中的正式課程</h2><span className="micro">只讀公開版，不提供直接編輯</span></div><div className="v4-grid">{courses.map(item=><article className="v4-box" key={item.id}><span className="eyebrow">{item.published!.kind==="system"?"SYSTEM COURSE":"STANDALONE COURSE"} / VERSION {item.revision}</span><h2 style={{margin:"16px 0"}}>{item.published!.title}</h2><p>{item.published!.summary}</p><div className="v4-inline-actions"><Go to={`courses/${item.id}`}>查看公開內容</Go><Btn onClick={()=>create(item.id)}>提出修改建議</Btn></div></article>)}</div></section></>:<><div className="v4-alert">目前全部是線上一對一。4、12、24、48 堂及客製價格都以新版本提案送審，不改舊生已買的方案。</div><div className="x-action-bar"><p>先設定建議售價，再等平台核准上架。</p><Btn primary onClick={()=>setOfferId("new")}>＋ 客製課程包提案</Btn></div><div className="x-grid four">{state.offers.filter(item=>item.teacherId===actor.id).map(item=><PackageCard key={item.id} offer={item} edit={()=>setOfferId(item.id)}/>)}</div><p className="footnote">固定制／預約制是排課方式，不是收費週期。設定價格不會直接改老師的分潤合約。</p></>}{offerId&&<PackageEditor id={offerId} close={()=>setOfferId(null)}/>}<Foot/></>;
}
function PackageCard({offer,edit}:{offer:PackageOffer;edit:()=>void}) {const item=offer.draft;return <article className="x-price-card"><div className="row between"><Flag active={Boolean(item.targetStudentId)}>{item.targetStudentId?"指定學生報價":"一對一課程包"}</Flag><Flag>{statusName(offer.status)}</Flag></div><h3>{item.count}<small>堂課</small></h3><span className="small">{item.title}</span><p>{modeName(item.mode)} · 每堂 {item.duration} 分鐘</p><div className="x-price">{money(item.unitPrice===null?null:item.count*item.unitPrice)}<small>每堂 {money(item.unitPrice)} · 示意售價</small></div><p>{item.expiryLabel}</p><div className="x-actions"><Btn onClick={edit}>設定售價</Btn></div></article>}
function PackageEditor({id,close}:{id:string;close:()=>void}) {
  const {state,actor,dispatch}=usePrototype();const {notify}=useWorkspaceActions();const existing=state.offers.find(item=>item.id===id&&item.teacherId===actor.id);const [savedId,setSavedId]=useState(existing?.id);const [content,setContent]=useState<OfferContent>(existing?.draft||{title:"客製一對一課程包",count:8,unitPrice:1000,mode:"flexible",duration:50,expiryLabel:"依正式課程包規則",targetStudentId:null,note:""});
  const set=<K extends keyof OfferContent>(key:K,value:OfferContent[K])=>setContent({...content,[key]:value});
  function save(submit:boolean){const result=dispatch({type:"saveOffer",id:savedId,content});if(!result.ok)return notify(result.error!);setSavedId(result.id);if(submit){const sent=dispatch({type:"submitOffer",id:result.id!});notify(sent.ok?"價格快照已送平台審核，公開版與舊已購快照不變。":sent.error!);if(sent.ok)close()}else notify("定價草稿已保存，公開價格沒有改變。")}
  return <Modal title={existing?"設定課程包售價":"建立客製課程包"} onClose={close}><p className="x-copy">設定新上架版本。學生已買的價格、剩餘堂數不會跟著改。</p><Field label="課程包名稱" value={content.title} onChange={value=>set("title",value)}/><div className="x-grid"><Field label="堂數" type="number" value={content.count} onChange={value=>set("count",Number(value))}/><Field label="每堂單價・新台幣整數" type="number" value={content.unitPrice??""} onChange={value=>set("unitPrice",value===""?null:Number(value))}/></div><div className="x-total"><span>課程包總價<small>堂數 × 每堂單價</small></span><strong>{money(content.unitPrice===null?null:content.count*content.unitPrice)}</strong></div><div className="x-grid"><Select label="支援排課方式" value={content.mode} onChange={value=>set("mode",value as OfferContent["mode"])} options={[["fixed","固定制"],["flexible","預約制"],["both","兩種都可"]]}/><Select label="公開／指定學生報價" value={content.targetStudentId||""} onChange={value=>set("targetStudentId",value||null)} options={[["","公開課程包"],...state.students.filter(item=>item.teacherId===actor.id&&item.relation==="private").map(item=>[item.id,`只給 ${item.name}`] as [string,string])]}/></div><Field label="效期說明・尚不制定自動規則" value={content.expiryLabel} onChange={value=>set("expiryLabel",value)}/><Area label="課程包說明" value={content.note} onChange={value=>set("note",value)}/><p className="dialog-note">每堂 {content.duration} 分鐘。指定學生報價不會出現在公開老師頁；此處不收款、不配堂數。送審前須已讀老師守則。</p><div className="x-actions"><Btn onClick={()=>save(false)}>儲存定價草稿</Btn><Btn primary onClick={()=>save(true)}>送平台審核</Btn></div></Modal>;
}
function ProposalEditor({id}:{id:string}) {
  const {state,actor,dispatch}=usePrototype();const {notify,confirm}=useWorkspaceActions();const router=useRouter();const proposal=state.proposals.find(item=>item.id===id&&item.teacherId===actor.id);const [content,setContent]=useState<CourseContent>(proposal?.content||{title:"",summary:"",kind:"system",billing:"membership",price:null,objective:"",outline:"",resourceName:""});const [audience,setAudience]=useState(proposal?.audience||"");const [rightsNote,setRightsNote]=useState(proposal?.rightsNote||"");const [proRequested,setPro]=useState(proposal?.proRequested||false);const [rights,setRights]=useState(false);
  if(!proposal)return <Empty title="尚未選擇自己的提案">請從我的課程開啟。<Go to="teacher/courses">回我的課程</Go></Empty>;
  const editable=["draft","changes"].includes(proposal.status);const set=<K extends keyof CourseContent>(key:K,value:CourseContent[K])=>setContent({...content,[key]:value});
  function save(){const result=dispatch({type:"saveProposal",id,content,audience,rightsNote,proRequested});notify(result.ok?"已保存提案草稿，沒有改動正式課程。":result.error!);return result.ok}
  function submit(){if(!rights||!policiesAccepted(state,actor))return notify("請先完整閱讀老師守則，並勾選素材權利確認。");if(!save())return;confirm("確認送出這份提案快照",<><h3>{content.title}</h3><p>{content.summary}</p><p>教學成果：{content.objective}</p><p>對象：{audience}</p><p>課綱：{content.outline}</p><p>素材來源：{rightsNote}</p><p>送審不會上架；內容變更須另開修訂版。</p></>,()=>{const result=dispatch({type:"submitProposal",id,rightsConfirmed:rights});notify(result.ok?"提案快照已送審，平台可匯入正式課程草稿。":result.error!);return result.ok})}
  return <><Header eyebrow="COURSE PROPOSAL / 從想法開始，而不是直接上架" title="課程提案" sub={proposal.baseCourseId?"為既有課程提出改版建議，不會覆寫公開內容。":"向平台提出新的教學內容建議。"} tools={<Go to="teacher/courses">回我的課程</Go>}/><div className="v4-steps"><span className="now">老師提案</span><span>平台審核</span><span>管理員編輯</span><span>預覽與發布</span></div><div className="v4-editor"><section><div className="v4-alert">{editable?"你正在編輯「提案」，不是正式課程。":"這份已送出的快照不再修改。要變更內容，請另開修訂版本。"}{proposal.reviewNote&&<p>平台回覆：{proposal.reviewNote}</p>}</div><fieldset disabled={!editable} style={{border:0,padding:0,margin:0}}><Field label="提案名稱" value={content.title} onChange={value=>set("title",value)}/><Select label="內容類型" value={content.kind} onChange={value=>set("kind",value as CourseContent["kind"])} options={[["system","系統課程"],["standalone","單品課"]]}/><Area label="課程簡介" value={content.summary} onChange={value=>set("summary",value)}/><Field label="希望學生最後做到什麼？" value={content.objective} onChange={value=>set("objective",value)}/><Field label="適合什麼樣的學生？" value={audience} onChange={setAudience}/><Area label="章節與單元提案・一行一個" value={content.outline} onChange={value=>set("outline",value)}/><Select label="建議上架方式・由平台確認" value={content.billing} onChange={value=>set("billing",value as CourseContent["billing"])} options={[["membership","申請加入平台會員目錄"],["one_time","建議單次購買"]]}/><Field label="建議單品售價・選填，非會員月費" value={content.price??""} type="number" onChange={value=>set("price",value===""?null:Number(value))}/><Area label="素材來源／授權說明與其他備註" value={rightsNote} onChange={setRightsNote}/><div className="x-field"><label className="x-label" htmlFor="proposal-file">提案附件・只記本地檔名</label><input id="proposal-file" type="file" accept=".pdf,.mp4,.jpg,.png" onChange={event=>set("resourceName",event.target.files?.[0]?.name||"")}/><small>{content.resourceName||"不讀取或上傳教材內容。"}</small></div><Check label="申請此課支援 Pro 影片指導" checked={proRequested} onChange={setPro}/><Check label="已閱讀提案守則，素材具備必要使用權利" checked={rights} onChange={setRights}/></fieldset><div className="v4-inline-actions">{editable?<><Btn onClick={save}>保存提案草稿</Btn><Btn primary onClick={submit}>送平台審核</Btn></>:<Btn onClick={()=>{const result=dispatch({type:"reviseProposal",id});if(result.ok)router.push(`${base}/teacher/proposals/${result.id}`);else notify(result.error!)}}>另開修訂版本</Btn>}</div></section><aside className="v4-guide"><h3>提交前，先確認這些事。</h3><p>老師不直接新增正式課程、不改公開版本，也不能自行選擇收入歸屬或開啟會員權益。</p><p>提案要說清楚成果、對象、章節與素材來源。會員目錄、Pro 服務與上架时间，由平台決定。</p><p>已上架內容若需修改，另送版本，不能讓修改立刻影響學生。</p><Go to="teacher/policies">閱讀老師提案守則</Go><p>{policiesAccepted(state,actor)?"本頁已讀目前老師守則。":"目前尚未完整閱讀老師守則。"}</p></aside></div><Foot/></>;
}
export function TeacherProfilePage() {
  const {state,actor,dispatch}=usePrototype();const {notify}=useWorkspaceActions();const teacher=state.teachers.find(item=>item.id===actor.id)!;const [profile,setProfile]=useState<TeacherProfile>(teacher.draft);const [preview,setPreview]=useState(false);const set=<K extends keyof TeacherProfile>(key:K,value:TeacherProfile[K])=>setProfile({...profile,[key]:value});
  function save(submit:boolean){const result=dispatch({type:"saveProfile",teacherId:actor.id,profile});if(!result.ok)return notify(result.error!);if(submit){const sent=dispatch({type:"submitProfile",teacherId:actor.id});notify(sent.ok?"展示頁快照已送審，公開版尚未變更。":sent.error!)}else notify("展示頁草稿已保存。")}
  return <><Header eyebrow="YOUR PUBLIC PROFILE / 先讓學生認識你" title="我的展示頁" sub="這些內容會組成公開老師介紹頁，也可以申請放進首頁師資區。"/><div className="x-action-bar"><Flag>{statusName(teacher.status)}</Flag><Btn onClick={()=>setPreview(true)}>預覽草稿</Btn></div><div className="x-editor"><section><div className="row" style={{marginBottom:28}}><Image unoptimized src={profile.photo||`${base}/guitar.jpg`} width={90} height={120} style={{width:90,height:120,objectFit:"cover",borderRadius:6}} alt={profile.photo?"老師本地展示圖片":"吉他概念影像，並非實際師資照"}/><div className="x-field" style={{margin:0,flex:1}}><label className="x-label" htmlFor="profile-photo">老師介紹照</label><input type="file" id="profile-photo" accept="image/jpeg,image/png,image/webp" onChange={event=>{const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024)return notify("請選擇 5 MB 內的 JPG、PNG 或 WebP 圖片。");const reader=new FileReader();reader.onload=()=>set("photo",String(reader.result));reader.readAsDataURL(file)}}/><small>只在目前頁面讀取圖片預覽，單張上限 5 MB；沒有上傳服務。</small></div></div><Field label="顯示名稱" value={profile.name} onChange={value=>set("name",value)}/><Field label="一句話教學介紹" value={profile.headline} onChange={value=>set("headline",value)}/><Area label="關於我／教學方式" value={profile.about} onChange={value=>set("about",value)}/><Field label="擅長項目" value={profile.specialties} onChange={value=>set("specialties",value)}/><div className="x-bottom-actions"><Btn onClick={()=>save(false)}>儲存草稿</Btn><Btn primary onClick={()=>save(true)}>送出展示頁審核</Btn></div></section><aside className="x-summary"><div className="x-panel"><h3>介紹頁上顯示什麼？</h3><Check label="系統課程" checked={profile.showSystem} onChange={value=>set("showSystem",value)}/><Check label="單品課程" checked={profile.showStandalone} onChange={value=>set("showStandalone",value)}/><Check label="一對一課程包" checked={profile.showPrivate} onChange={value=>set("showPrivate",value)}/><p>首頁推薦由管理員核准設定；指定學生的客製報價不公開。</p></div><div className="x-panel"><h3>訪客會怎麼找到你？</h3><p>首頁老師展示卡 → 老師介紹 → 已發布課程或一對一包。</p><Go to={`teachers/${actor.id}?tab=private`}>查看目前公開版</Go></div></aside></div>{preview&&<Modal title="老師展示頁草稿預覽" onClose={()=>setPreview(false)}><Flag>草稿，尚未公開</Flag><h2 style={{marginTop:18}}>{profile.name}</h2><p className="x-copy">{profile.headline}</p><p className="t-prewrap">{profile.about}</p><p>{profile.specialties}</p><p className="dialog-note">公開課程與已購權益不受預覽影響。</p></Modal>}<Foot/></>;
}
