# LOCAL-only true multi-session audit for P1-6A transaction reconciliation.
# Explicit entry-point revalidation remains separately classified as P1-6B.
[CmdletBinding()]param([ValidatePattern('^supabase_db_[A-Za-z0-9_-]+$')][string]$ContainerName)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$docker=(Get-Command docker -ErrorAction Stop).Source
if(-not $ContainerName){$names=@(& $docker --host 'npipe:////./pipe/docker_engine' ps --format '{{.Names}}'|Where-Object{$_ -like 'supabase_db_*'});if($names.Count-ne 1){throw "Expected one local Supabase DB container; found $($names.Count)."};$ContainerName=$names[0]}
function Invoke-Db([string]$Sql){$out=& $docker --host 'npipe:////./pipe/docker_engine' exec $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At -c $Sql 2>&1|Out-String;[pscustomobject]@{ExitCode=$LASTEXITCODE;Output=$out.Trim()}}
function Start-Db([string]$Sql){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$docker;$i.Arguments="--host npipe:////./pipe/docker_engine exec -i $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At";$i.UseShellExecute=$false;$i.RedirectStandardInput=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$i;[void]$p.Start();$p.StandardInput.Write($Sql);$p.StandardInput.Close();$p}
function Wait-Db($Process){$o=$Process.StandardOutput.ReadToEndAsync();$e=$Process.StandardError.ReadToEndAsync();if(-not $Process.WaitForExit(30000)){$Process.Kill();throw 'DB session timeout'};[pscustomobject]@{ExitCode=$Process.ExitCode;Output=(($o.Result+[Environment]::NewLine+$e.Result).Trim())}}
function Race([string[]]$Sql){$ps=@($Sql|ForEach-Object{Start-Db $_});@($ps|ForEach-Object{Wait-Db $_})}
function Auth([string]$User,[string]$Body){"begin;set local role authenticated;select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','$User',true);set local statement_timeout='15s';$Body commit;"}
function Must($Result,[string]$Name){if($Result.ExitCode-ne 0){throw "$Name failed: $($Result.Output)"}}
function Scalar([string]$Sql){$r=Invoke-Db $Sql;Must $r 'scalar query';($r.Output-split'[\r\n]+')[-1]}
function Inspect($Results){foreach($r in $Results){if($r.Output-match'ERROR:\s+40P01'){$script:stats.Deadlock++};if($r.Output-match'ERROR:\s+23505'){$script:stats.UniqueViolation++};if($r.Output-match'ERROR:\s+23P01'){$script:stats.ExclusionViolation++};if($r.Output-match'ERROR:\s+P0001'){$script:stats.Domain++};if($r.Output-match'ERROR:\s+23[0-9A-Z]{3}'-and$r.Output-notmatch'ERROR:\s+(23505|23P01)'){$script:stats.UnexpectedIntegrity++}}}
function Assert-NoLeak($Results,[string]$Name){if(@($Results|Where-Object{$_.ExitCode-ne 0-and$_.Output-notmatch'ERROR:\s+P0001'}).Count-ne 0){throw "$Name leaked non-domain error: $($Results.Output-join' | ')"}}

$stats=[ordered]@{Deadlock=0;UniqueViolation=0;ExclusionViolation=0;UnexpectedIntegrity=0;Domain=0;Partial=0}
$student='7c000000-0000-0000-0000-000000000001';$teacher='7c000000-0000-0000-0000-000000000002';$admin='7c000000-0000-0000-0000-000000000003';$relationship='7c000000-0000-0000-0000-000000000010'
$ents=@('7c000000-0000-0000-0000-000000000020','7c000000-0000-0000-0000-000000000021','7c000000-0000-0000-0000-000000000022','7c000000-0000-0000-0000-000000000023')
$cleanup="begin;set local session_replication_role='replica';delete from public.lesson_records where lesson_id in(select id from public.lessons where student_user_id='$student');delete from public.audit_logs where actor_user_id in('$student','$teacher','$admin');delete from public.bookings where student_user_id='$student';delete from public.lesson_credit_ledger where beneficiary_user_id='$student';delete from public.lesson_credit_reservations where beneficiary_user_id='$student';delete from public.lessons where student_user_id='$student';delete from public.teacher_availability_exceptions where teacher_user_id='$teacher';delete from public.teacher_scheduling_settings where teacher_user_id='$teacher';delete from public.entitlement_revoke_operations where entitlement_id in('$($ents[0])','$($ents[1])','$($ents[2])','$($ents[3])');delete from public.entitlements where beneficiary_user_id='$student';delete from public.student_teacher_relationships where id='$relationship';delete from public.teacher_public_profiles where public_slug='p16-race-teacher';delete from public.teacher_profiles where user_id='$teacher';delete from public.public_profiles where user_id in('$student','$teacher','$admin');delete from public.user_roles where user_id in('$student','$teacher','$admin');delete from public.profiles where user_id in('$student','$teacher','$admin');delete from auth.users where id in('$student','$teacher','$admin');commit;"
$setup=$cleanup+"insert into auth.users(id,email)values('$student','p16-race-student@example.invalid'),('$teacher','p16-race-teacher@example.invalid'),('$admin','p16-race-admin@example.invalid');insert into public.user_roles(user_id,role)values('$teacher','teacher'),('$admin','admin');insert into public.teacher_profiles(user_id,public_slug,bio,teaching_status,is_public,teaching_modes,trial_price_twd,default_meeting_provider,default_meeting_url)values('$teacher','p16-race-teacher','Race fixture','active',true,array['online']::public.teaching_mode[],500,'manual_google_meet','https://meet.google.com/abc-defg-hij');insert into public.student_teacher_relationships(id,student_user_id,teacher_user_id,relationship_status,preferred_mode)values('$relationship','$student','$teacher','active','online');insert into public.teacher_scheduling_settings(teacher_user_id,timezone,minimum_booking_notice_minutes,booking_horizon_days,slot_interval_minutes)values('$teacher','UTC',0,90,10);insert into public.teacher_availability_exceptions(teacher_user_id,exception_kind,starts_at,ends_at,reason,created_by)values('$teacher','opening',(current_date+14)::timestamp+time '08:00',(current_date+14)::timestamp+time '23:30','P1-6 race opening','$teacher');insert into public.entitlements(id,beneficiary_user_id,teacher_scope_user_id,entitlement_type,status,starts_at,expires_at,product_name_snapshot,booking_mode_eligibility,lesson_duration_minutes)values('$($ents[0])','$student','$teacher','lesson_package','active',now()-interval '1 day',now()+interval '6 months','Race A','both',50),('$($ents[1])','$student','$teacher','lesson_package','active',now()-interval '1 day',now()+interval '6 months','Race B','both',50),('$($ents[2])','$student','$teacher','lesson_package','active',now()-interval '1 day',now()+interval '6 months','Race C','both',50),('$($ents[3])','$student','$teacher','lesson_package','active',now()-interval '1 day',now()+interval '6 months','Race D','both',50);insert into public.lesson_credit_ledger(entitlement_id,beneficiary_user_id,entry_type,available_delta,operation_key,reason_code)values('$($ents[0])','$student','allocation',1,'p16-race-allocation-a','fixture'),('$($ents[1])','$student','allocation',1,'p16-race-allocation-b','fixture'),('$($ents[2])','$student','allocation',1,'p16-race-allocation-c','fixture'),('$($ents[3])','$student','allocation',1,'p16-race-allocation-d','fixture');"
function Slot([int]$Hour){"((current_date+14)::timestamp+interval '$Hour hours') at time zone 'UTC'"}
function Book([string]$Entitlement,[int]$Hour,[string]$Key){"select public.create_lesson_booking('$student','$teacher','$relationship','$Entitlement',$(Slot $Hour),'UTC','$Key','P1-6 race booking');"}
try{
  Must (Invoke-Db $setup) 'setup'
  Must (Invoke-Db (Auth $student "$(Book $ents[0] 10 'p16-race-booking-a-0001')$(Book $ents[1] 12 'p16-race-booking-b-0001')$(Book $ents[2] 14 'p16-race-booking-c-0001')$(Book $ents[3] 16 'p16-race-booking-d-0001')")) 'create race bookings'
  $bookingA=Scalar "select id from public.bookings where idempotency_key='p16-race-booking-a-0001'";$bookingB=Scalar "select id from public.bookings where idempotency_key='p16-race-booking-b-0001'";$bookingC=Scalar "select id from public.bookings where idempotency_key='p16-race-booking-c-0001'";$bookingD=Scalar "select id from public.bookings where idempotency_key='p16-race-booking-d-0001'";$lessonB=Scalar "select lesson_id from public.bookings where id='$bookingB'"
  Must (Invoke-Db "update public.lessons set starts_at=now()-interval '1 hour',ends_at=now()-interval '10 minutes' where id='$lessonB';update public.bookings set starts_at=now()-interval '1 hour',ends_at=now()-interval '10 minutes' where id='$bookingB';") 'prepare completion race'

  $race=Race @((Auth $admin "select pg_sleep(.2);select public.admin_revoke_entitlement('$($ents[0])','Concurrent revoke A','p16-race-revoke-a-0001');"),(Auth $student "select pg_sleep(.2);select public.reschedule_lesson_booking('$bookingA',$(Slot 16),'UTC','Concurrent reschedule A');"));Inspect $race;Assert-NoLeak $race 'revoke vs reschedule';$state=Scalar "select e.status||'|'||r.status||'|'||b.status||'|'||l.status from public.bookings b join public.lessons l on l.id=b.lesson_id join public.lesson_credit_reservations r on r.id=b.credit_reservation_id join public.entitlements e on e.id=r.entitlement_id where b.id='$bookingA'";if($state-eq'revoked|released|cancelled|admin_cancelled'){'A [PASS P1-6B] revoke vs reschedule leaves no orphan or partial mutation'}else{$stats.Partial++;throw "A inconsistent state $state"}

  $race=Race @((Auth $admin "select pg_sleep(.2);select public.admin_revoke_entitlement('$($ents[1])','Concurrent revoke B','p16-race-revoke-b-0001');"),(Auth $teacher "select pg_sleep(.2);select public.complete_lesson_booking('$bookingB','Visible','Private','Summary','Goal','Homework');"));Inspect $race;Assert-NoLeak $race 'revoke vs complete';$state=Scalar "select e.status||'|'||r.status||'|'||b.status||'|'||l.status from public.bookings b join public.lessons l on l.id=b.lesson_id join public.lesson_credit_reservations r on r.id=b.credit_reservation_id join public.entitlements e on e.id=r.entitlement_id where b.id='$bookingB'";if($state-in @('revoked|consumed|completed|completed','revoked|released|cancelled|admin_cancelled')){"B [PASS P1-6B] revoke vs complete serializes to a valid terminal state; final=$state"}else{$stats.Partial++;throw "B inconsistent state $state"}

  $race=Race @((Auth $admin "select pg_sleep(.2);select public.admin_revoke_entitlement('$($ents[2])','Concurrent revoke C','p16-race-revoke-c-0001');"),(Auth $student "select pg_sleep(.2);select public.cancel_lesson_booking('$bookingC','released','Concurrent cancel C');"));Inspect $race;Assert-NoLeak $race 'revoke vs cancel';$state=Scalar "select e.status||'|'||r.status||'|'||b.status||'|'||l.status from public.bookings b join public.lessons l on l.id=b.lesson_id join public.lesson_credit_reservations r on r.id=b.credit_reservation_id join public.entitlements e on e.id=r.entitlement_id where b.id='$bookingC'";$releases=[int](Scalar "select count(*) from public.lesson_credit_ledger where reservation_id=(select credit_reservation_id from public.bookings where id='$bookingC') and entry_type='release'");if($state-in @('revoked|released|cancelled|student_cancelled','revoked|released|cancelled|admin_cancelled') -and $releases-le 1){"C [PASS] revoke vs cancel is consistent; final=$state release entries=$releases"}else{$stats.Partial++;throw "C inconsistent state $state releases=$releases"}

  $race=Race @((Auth $student "select pg_sleep(.2);select public.cancel_lesson_booking('$bookingD','released','Concurrent source invalidation D');"),(Auth $student "select pg_sleep(.2);select public.reschedule_lesson_booking('$bookingD',$(Slot 20),'UTC','Concurrent reschedule D');"));Inspect $race;Assert-NoLeak $race 'source invalidation vs reschedule';$state=Scalar "select e.status||'|'||r.status||'|'||b.status||'|'||l.status from public.bookings b join public.lessons l on l.id=b.lesson_id join public.lesson_credit_reservations r on r.id=b.credit_reservation_id join public.entitlements e on e.id=r.entitlement_id where b.id='$bookingD'";$releases=[int](Scalar "select count(*) from public.lesson_credit_ledger where reservation_id=(select credit_reservation_id from public.bookings where id='$bookingD') and entry_type='release'");if($state-eq'active|released|cancelled|student_cancelled' -and $releases-eq 1){"D [PASS P1-6B] source invalidation vs reschedule has one terminal outcome; release entries=$releases"}else{$stats.Partial++;throw "D inconsistent state $state releases=$releases"}

  if($stats.Deadlock-ne 0-or$stats.UniqueViolation-ne 0-or$stats.ExclusionViolation-ne 0-or$stats.UnexpectedIntegrity-ne 0-or$stats.Partial-ne 0){throw "Unexpected result: 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23P01=$($stats.ExclusionViolation) unexpected23xxx=$($stats.UnexpectedIntegrity) partial=$($stats.Partial)"}
  "SUMMARY 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23P01=$($stats.ExclusionViolation) unexpected23xxx=$($stats.UnexpectedIntegrity) domain=$($stats.Domain) partial=$($stats.Partial)"
}finally{Must (Invoke-Db $cleanup) 'cleanup'}
