# LOCAL-only true multi-session validation for same-series Fixed refresh.
[CmdletBinding()]param([ValidatePattern('^supabase_db_[A-Za-z0-9_-]+$')][string]$ContainerName)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$docker=(Get-Command docker -ErrorAction Stop).Source
if(-not $ContainerName){$names=@(& $docker --host 'npipe:////./pipe/docker_engine' ps --format '{{.Names}}'|Where-Object{$_ -like 'supabase_db_*'});if($names.Count-ne 1){throw "Expected one local Supabase DB container; found $($names.Count)."};$ContainerName=$names[0]}
$run='refresh-race-'+[guid]::NewGuid().ToString('N');$sessions=[Collections.Generic.List[object]]::new()
function Start-Db([string]$Sql,[string]$Name,[switch]$KeepInputOpen){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$docker;$i.Arguments="--host npipe:////./pipe/docker_engine exec -i $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At";$i.UseShellExecute=$false;$i.RedirectStandardInput=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$i;[void]$p.Start();$s=[pscustomobject]@{Process=$p;Name=$Name;Stdout=$p.StandardOutput.ReadToEndAsync();Stderr=$p.StandardError.ReadToEndAsync()};$sessions.Add($s);$p.StandardInput.WriteLine("set application_name='$Name';set statement_timeout='20s';set idle_in_transaction_session_timeout='30s';");$p.StandardInput.WriteLine($Sql);$p.StandardInput.Flush();if(-not$KeepInputOpen){$p.StandardInput.Close()};$s}
function Wait-Db($Session){if(-not$Session.Process.WaitForExit(30000)){throw "Session timeout: $($Session.Name)"};[pscustomobject]@{ExitCode=$Session.Process.ExitCode;Output=(($Session.Stdout.Result+[Environment]::NewLine+$Session.Stderr.Result).Trim())}}
function Invoke-Db([string]$Sql){Wait-Db (Start-Db $Sql "$run-observer")}
function Must($Result,[string]$Name){if($Result.ExitCode-ne 0){throw "$Name failed: $($Result.Output)"}}
function Value([string]$Sql){$r=Invoke-Db $Sql;Must $r 'value query';($r.Output-split'[\r\n]+')[-1]}
function Db-Uuid([string]$Sql){$r=Invoke-Db $Sql;Must $r 'UUID query';$m=[regex]::Matches($r.Output,'(?i)[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}');if($m.Count-eq 0){throw "No UUID found: $($r.Output)"};$m[$m.Count-1].Value}
function Count([string]$Sql,[int]$Expected,[string]$Name){$actual=[int](Value $Sql);if($actual-ne$Expected){$script:stats.Partial++;throw "$Name expected $Expected got $actual"}}
function Auth([string]$User,[string]$Body){"begin;set local role authenticated;select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','$User',true);$Body commit;"}
function Wait-Condition([string]$Sql,[string]$Name){$timer=[Diagnostics.Stopwatch]::StartNew();do{if((Value $Sql)-eq't'){return};Start-Sleep -Milliseconds 100}while($timer.Elapsed.TotalSeconds-lt 12);throw "Timed out waiting for $Name"}
function Inspect($Results){foreach($r in $Results){if($r.Output-match'ERROR:\s+40P01'){$script:stats.Deadlock++};if($r.Output-match'ERROR:\s+23505'){$script:stats.UniqueViolation++};if($r.Output-match'ERROR:\s+23P01'){$script:stats.ExclusionViolation++};if($r.Output-match'ERROR:\s+23[0-9A-Z]{3}'-and$r.Output-notmatch'ERROR:\s+(23505|23P01)'){$script:stats.UnexpectedIntegrity++}}}
function Refresh-Race([string]$Series,[string]$Left,[string]$Right){
  $gateName="$run-gate";$leftName="$run-left";$rightName="$run-right"
  $gate=Start-Db "begin;select id from public.recurring_lesson_series where id='$Series' for update;" $gateName -KeepInputOpen
  try{
    Wait-Condition "select exists(select 1 from pg_stat_activity where application_name='$gateName' and state='idle in transaction')" 'series row gate'
    $leftSession=Start-Db $Left $leftName;$rightSession=Start-Db $Right $rightName
    Wait-Condition "select count(*)=2 from pg_stat_activity where application_name in('$leftName','$rightName') and wait_event_type='Lock'" 'two independent refresh sessions'
    Write-Host 'REFRESH barrier: two independent PostgreSQL sessions confirmed'
    $gate.Process.StandardInput.WriteLine('commit;');$gate.Process.StandardInput.Close();Must (Wait-Db $gate) 'release series gate'
    @((Wait-Db $leftSession),(Wait-Db $rightSession))
  }finally{if(-not$gate.Process.HasExited){try{$gate.Process.StandardInput.WriteLine('rollback;');$gate.Process.StandardInput.Close()}catch{}}}
}
$stats=[ordered]@{Deadlock=0;UniqueViolation=0;ExclusionViolation=0;UnexpectedIntegrity=0;Partial=0}
$studentA='7b000000-0000-0000-0000-000000000001';$studentB='7b000000-0000-0000-0000-000000000002';$teacher='7b000000-0000-0000-0000-000000000003';$relationshipA='7b000000-0000-0000-0000-000000000010';$relationshipB='7b000000-0000-0000-0000-000000000011';$entitlement='7b000000-0000-0000-0000-000000000020';$series=$null
$cleanup="begin;set local session_replication_role='replica';delete from public.lesson_records where lesson_id in(select id from public.lessons where student_user_id in('$studentA','$studentB'));delete from public.audit_logs where actor_user_id in('$studentA','$studentB','$teacher');delete from public.bookings where student_user_id in('$studentA','$studentB');delete from public.lesson_credit_ledger where beneficiary_user_id in('$studentA','$studentB');delete from public.lesson_credit_reservations where beneficiary_user_id in('$studentA','$studentB');delete from public.recurring_lesson_series_exceptions where actor_user_id in('$studentA','$studentB','$teacher');delete from public.recurring_lesson_occurrences where student_user_id in('$studentA','$studentB');delete from public.lessons where student_user_id in('$studentA','$studentB');delete from public.recurring_lesson_series where student_user_id in('$studentA','$studentB');delete from public.teacher_availability_rules where teacher_user_id='$teacher';delete from public.teacher_scheduling_settings where teacher_user_id='$teacher';delete from public.entitlements where beneficiary_user_id in('$studentA','$studentB');delete from public.student_teacher_relationships where id in('$relationshipA','$relationshipB');delete from public.teacher_public_profiles where public_slug='refresh-race-teacher';delete from public.teacher_profiles where user_id='$teacher';delete from public.public_profiles where user_id in('$studentA','$studentB','$teacher');delete from public.user_roles where user_id in('$studentA','$studentB','$teacher');delete from public.profiles where user_id in('$studentA','$studentB','$teacher');delete from auth.users where id in('$studentA','$studentB','$teacher');commit;"
$setup=$cleanup+"insert into auth.users(id,email)values('$studentA','refresh-race-a@example.invalid'),('$studentB','refresh-race-b@example.invalid'),('$teacher','refresh-race-teacher@example.invalid');insert into public.user_roles(user_id,role)values('$teacher','teacher');insert into public.teacher_profiles(user_id,public_slug,bio,teaching_status,is_public,teaching_modes,trial_price_twd,default_meeting_provider,default_meeting_url)values('$teacher','refresh-race-teacher','Refresh race','active',true,array['online']::public.teaching_mode[],500,'manual_google_meet','https://meet.google.com/abc-defg-hij');insert into public.student_teacher_relationships(id,student_user_id,teacher_user_id,relationship_status,preferred_mode)values('$relationshipA','$studentA','$teacher','active','online'),('$relationshipB','$studentB','$teacher','active','online');insert into public.teacher_scheduling_settings(teacher_user_id,timezone,minimum_booking_notice_minutes,booking_horizon_days,slot_interval_minutes)values('$teacher','UTC',0,60,10);insert into public.teacher_availability_rules(teacher_user_id,weekday,local_start_time,local_end_time,timezone,effective_from,effective_until,created_by)select '$teacher',extract(dow from current_date+14)::smallint,'08:00','23:30','UTC',current_date,current_date+90,'$teacher';insert into public.entitlements(id,beneficiary_user_id,teacher_scope_user_id,entitlement_type,status,starts_at,expires_at,product_name_snapshot,booking_mode_eligibility,lesson_duration_minutes)values('$entitlement','$studentA','$teacher','lesson_package','active',now()-interval '1 day',now()+interval '6 months','Refresh race entitlement','fixed',50);insert into public.lesson_credit_ledger(entitlement_id,beneficiary_user_id,entry_type,available_delta,operation_key,reason_code)values('$entitlement','$studentA','allocation',4,'refresh-race-allocation-0001','fixture');"
try{
  Must (Invoke-Db $setup) 'setup'
  $series=Db-Uuid (Auth $teacher "select public.create_recurring_lesson_series('$studentA','$teacher','$relationshipA',null::uuid,extract(dow from current_date+14)::smallint,'10:00'::time,'UTC',50::smallint,current_date+14,current_date+70,'Refresh race series');")
  Must (Invoke-Db (Auth $teacher "select public.materialize_recurring_lesson_occurrence('$series',current_date+14,'$entitlement','refresh-race-materialized-0001');select public.materialize_recurring_lesson_occurrence('$series',current_date+21,null,'refresh-race-credit-required-0001');")) 'state controls'
  $beforeCount=[int](Value "select count(*) from public.recurring_lesson_occurrences where series_id='$series'")
  $beforeBinding=Value "select coalesce(lesson_id::text,'null')||'|'||coalesce(booking_id::text,'null') from public.recurring_lesson_occurrences where series_id='$series' and occurrence_date=current_date+14"
  $refresh=Auth $teacher "select public.refresh_recurring_series_occurrences('$series',current_date+60);"
  $race=Refresh-Race $series $refresh $refresh;Inspect $race
  if(@($race|Where-Object{$_.ExitCode-eq 0}).Count-ne 2){$stats.Partial++;throw "Concurrent refresh did not produce two legal outcomes: $($race.Output-join' | ')"}
  Count "select count(*) from public.recurring_lesson_occurrences where series_id='$series'" $beforeCount 'unchanged logical horizon'
  Count "select count(*) from(select occurrence_date from public.recurring_lesson_occurrences where series_id='$series' group by occurrence_date having count(*)>1)d" 0 'no duplicate logical occurrence'
  Count "select count(*) from public.recurring_lesson_occurrences where series_id='$series' and occurrence_date=current_date+28 and status='planned'" 1 'planned state retained'
  Count "select count(*) from public.recurring_lesson_occurrences where series_id='$series' and occurrence_date=current_date+21 and status='credit_required'" 1 'credit_required state retained'
  Count "select count(*) from public.recurring_lesson_occurrences where series_id='$series' and occurrence_date=current_date+14 and status='materialized'" 1 'materialized state retained'
  if((Value "select coalesce(lesson_id::text,'null')||'|'||coalesce(booking_id::text,'null') from public.recurring_lesson_occurrences where series_id='$series' and occurrence_date=current_date+14")-ne$beforeBinding){$stats.Partial++;throw 'materialized binding changed'}
  Count "select count(*) from public.bookings where recurring_series_id='$series'" 1 'one materialized Booking'
  Count "select count(*) from public.lessons l join public.bookings b on b.lesson_id=l.id where b.recurring_series_id='$series'" 1 'one materialized Lesson'
  'REFRESH [PASS] planned / credit_required / materialized states and binding retained'
  $collision=Invoke-Db (Auth $teacher "select public.create_recurring_lesson_series('$studentB','$teacher','$relationshipB',null::uuid,extract(dow from current_date+14)::smallint,'10:00'::time,'UTC',50::smallint,current_date+14,current_date+70,'External overlap control');")
  if($collision.ExitCode-eq 0-or$collision.Output-notmatch'ERROR:\s+P0001:\s+RECURRING_SERIES_CONFLICT'){$stats.Partial++;throw "External collision was not rejected correctly: $($collision.Output)"}
  'COLLISION [PASS] different overlapping series remains rejected'
  if($stats.Deadlock-ne 0-or$stats.UniqueViolation-ne 0-or$stats.ExclusionViolation-ne 0-or$stats.UnexpectedIntegrity-ne 0-or$stats.Partial-ne 0){throw "Unexpected result: 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23P01=$($stats.ExclusionViolation) unexpected23xxx=$($stats.UnexpectedIntegrity) partial=$($stats.Partial)"}
  "SUMMARY 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23P01=$($stats.ExclusionViolation) unexpected23xxx=$($stats.UnexpectedIntegrity) partial=$($stats.Partial)"
}finally{
  try{Must (Invoke-Db $cleanup) 'cleanup';Count "select count(*) from auth.users where id in('$studentA','$studentB','$teacher')" 0 'user cleanup';Count "select count(*) from public.recurring_lesson_series where student_user_id in('$studentA','$studentB')" 0 'series cleanup'}finally{foreach($s in $sessions){if(-not$s.Process.HasExited){try{$s.Process.Kill()}catch{}};$s.Process.Dispose()}}
}
