[CmdletBinding()]param([string]$ContainerName)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$docker=(Get-Command docker -ErrorAction Stop).Source
if(-not $ContainerName){$names=@(& $docker ps --format '{{.Names}}'|Where-Object{$_ -like 'supabase_db_*'});if($names.Count-ne 1){throw "Expected one local Supabase DB container; found $($names.Count)."};$ContainerName=$names[0]}
function Invoke-Db([string]$Sql){$out=& $docker exec $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At -c $Sql 2>&1|Out-String;[pscustomobject]@{ExitCode=$LASTEXITCODE;Output=$out.Trim()}}
function Start-Db([string]$Sql){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$docker;$i.Arguments="exec -i $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At";$i.UseShellExecute=$false;$i.RedirectStandardInput=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$i;[void]$p.Start();$p.StandardInput.Write($Sql);$p.StandardInput.Close();$p}
function Wait-Db($Process){$o=$Process.StandardOutput.ReadToEndAsync();$e=$Process.StandardError.ReadToEndAsync();if(-not $Process.WaitForExit(30000)){$Process.Kill($true);throw 'DB session timeout'};[pscustomobject]@{ExitCode=$Process.ExitCode;Output=(($o.Result+"`n"+$e.Result).Trim())}}
function Race([string[]]$Sql){$ps=@($Sql|ForEach-Object{Start-Db $_});@($ps|ForEach-Object{Wait-Db $_})}
function Auth([string]$User,[string]$Body){"begin;set local role authenticated;select set_config('request.jwt.claim.sub','$User',true);set local statement_timeout='15s';$Body commit;"}
function Must($Result,[string]$Name){if($Result.ExitCode-ne 0){throw "$Name failed: $($Result.Output)"}}
function Uuid($Result){$matches=[regex]::Matches($Result.Output,'(?i)[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}');if($matches.Count-eq 0){throw "No UUID in DB session output: $($Result.Output)"};$matches[$matches.Count-1].Value}
function Count([string]$Sql,[int]$Expected,[string]$Name){$r=Invoke-Db $Sql;Must $r $Name;$n=[int](($r.Output-split"`r?`n")[-1]);if($n-ne$Expected){throw "$Name expected $Expected got $n"}}
$stats=[ordered]@{Deadlock=0;UniqueViolation=0;DomainRejection=0;IntegrityRejection=0;PartialState=0}
function Inspect-Race($Results){foreach($result in $Results){if($result.Output -match 'ERROR:\s+40P01'){$stats.Deadlock++};if($result.Output -match 'ERROR:\s+23505'){$stats.UniqueViolation++};if($result.Output -match 'ERROR:\s+P0001'){$stats.DomainRejection++};if($result.Output -match 'ERROR:\s+23[0-9A-Z]{3}' -and $result.Output -notmatch 'ERROR:\s+23505'){$stats.IntegrityRejection++}}}
function Assert-One-Winner($Results,[string]$Name){if(@($Results|Where-Object{$_.ExitCode -eq 0}).Count-ne 1){throw "$Name expected exactly one winner: $($Results.Output-join' | ')"};if(@($Results|Where-Object{$_.ExitCode -ne 0 -and $_.Output -notmatch 'P0001'}).Count-ne 0){throw "$Name loser did not receive a domain rejection: $($Results.Output-join' | ')"}}
$buyer='71000000-0000-0000-0000-000000000001';$admin1='71000000-0000-0000-0000-000000000002';$admin2='71000000-0000-0000-0000-000000000003'
$cleanup="begin;set local session_replication_role='replica';delete from public.audit_logs where actor_user_id in ('$admin1','$admin2');delete from public.lesson_credit_ledger where beneficiary_user_id='$buyer';delete from public.lesson_credit_reservations where beneficiary_user_id='$buyer';delete from public.entitlement_expiry_history where entitlement_id in(select id from public.entitlements where beneficiary_user_id='$buyer');delete from public.entitlement_revoke_operations where entitlement_id in(select id from public.entitlements where beneficiary_user_id='$buyer');delete from public.entitlements where beneficiary_user_id='$buyer';delete from public.order_item_fulfillment_snapshots where order_item_id in(select oi.id from public.order_items oi join public.orders o on o.id=oi.order_id where o.buyer_user_id='$buyer');delete from public.order_fulfillment_events where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.payment_submissions where buyer_user_id='$buyer';delete from public.refunds where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.payments where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.order_items where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.orders where buyer_user_id='$buyer';delete from public.product_public_catalog where public_slug='epic4-race-product';delete from public.products where public_slug='epic4-race-product';delete from public.user_roles where user_id in('$buyer','$admin1','$admin2');delete from public.profiles where user_id in('$buyer','$admin1','$admin2');delete from auth.users where id in('$buyer','$admin1','$admin2');commit;"
$setup="$cleanup insert into auth.users(id,email) values('$buyer','epic4-race-buyer@example.invalid'),('$admin1','epic4-race-admin1@example.invalid'),('$admin2','epic4-race-admin2@example.invalid');insert into public.user_roles(user_id,role) values('$admin1','admin'),('$admin2','admin');insert into public.products(product_type,status,public_slug,name,currency,base_price_amount,owner_type,is_public,is_purchasable,published_at) values('lesson_package','active','epic4-race-product','Race Product','TWD',3200,'platform',true,true,now());insert into public.lesson_package_product_configs(product_id,lesson_count,validity_value,validity_unit,lesson_duration_minutes,booking_mode_eligibility)select id,4,6,'months',50,'flexible' from public.products where public_slug='epic4-race-product';"
try{
  Must (Invoke-Db $setup) 'setup'
  $checkout=Auth $buyer "select pg_sleep(.3);select public.create_checkout_order('epic4-race-product',1,'81111111-1111-4111-8111-111111111111');"
  $r=Race @($checkout,$checkout);Inspect-Race $r;$r|ForEach-Object{Must $_ 'same-key checkout'};$ids=@($r|ForEach-Object{Uuid $_});if($ids[0]-ne$ids[1]){throw 'checkout returned different IDs'};Count "select count(*) from public.orders where buyer_user_id='$buyer' and idempotency_key='81111111-1111-4111-8111-111111111111'" 1 'checkout count';'TEST 1 [PASS] same-key checkout: same order, no 23505'

  $order=$ids[0];$submit=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$order','Race Buyer','12345',null,'82222222-2222-4222-8222-222222222222');");Must $submit 'payment setup';$payment=Uuid $submit
  $confirm=Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$order','$payment','race-event-1','Concurrency validation');"
  $confirm2=Auth $admin2 "select pg_sleep(.3);select public.admin_confirm_payment('$order','$payment','race-event-1','Concurrency validation');"
  $r=Race @($confirm,$confirm2);Inspect-Race $r;$r|ForEach-Object{Must $_ 'double confirm'};Count "select count(*) from public.order_fulfillment_events where order_id='$order'" 1 'double-confirm event';Count "select count(*) from public.audit_logs where target_id='$payment'" 1 'double-confirm audit';'TEST 2 [PASS] double confirmation: one paid effect and one outbox event'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'83333333-3333-4333-8333-333333333333');");Must $new 'cancel race order';$o2=Uuid $new;$pay=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o2','Race Buyer','12345',null,'84444444-4444-4444-8444-444444444444');");Must $pay 'cancel race payment';$p2=Uuid $pay
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o2','$p2','race-event-2','Race confirm');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_cancel_order('$o2','Race cancel');"));Inspect-Race $r;if(@($r|Where-Object{$_.ExitCode -eq 0}).Count -ne 1){throw "cancel/payment expected one winner: $($r.Output-join' | ')"};$state=(Invoke-Db "select status::text||'|'||payment_status::text||'|'||(select count(*) from public.order_fulfillment_events where order_id='$o2') from public.orders where id='$o2'").Output;if(-not(@('paid|paid|1','cancelled|unpaid|0') -contains $state)){$stats.PartialState++;throw "partial cancel/payment state: $state"};'TEST 3 [PASS] cancel/payment race: consistent winner state'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'85555555-5555-4555-8555-555555555555');");Must $new 'expiry race order';$o3=Uuid $new;$pay=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o3','Race Buyer','12345',null,'86666666-6666-4666-8666-666666666666');");Must $pay 'expiry race payment';$p3=Uuid $pay;Must (Invoke-Db "update public.orders set expires_at=now()-interval '1 second' where id='$o3'") 'backdate expiry'
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o3','$p3','race-event-3','Race confirm');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_expire_order('$o3','Race expiry');"));Inspect-Race $r;if(@($r|Where-Object{$_.ExitCode -eq 0}).Count -ne 1){throw "expiry/payment expected one winner: $($r.Output-join' | ')"};$state=(Invoke-Db "select status::text||'|'||payment_status::text||'|'||(select count(*) from public.order_fulfillment_events where order_id='$o3') from public.orders where id='$o3'").Output;if(-not(@('paid|paid|1','expired|unpaid|0') -contains $state)){$stats.PartialState++;throw "partial expiry/payment state: $state"};'TEST 4 [PASS] expiry/payment race: consistent winner state'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'87777777-7777-4777-8777-777777777777');");Must $new 'different-payment order';$o4=Uuid $new
  $pa=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o4','Race Buyer','11111',null,'88888888-8888-4888-8888-888888888881');");Must $pa 'different payment A';$p4a=Uuid $pa
  $pb=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o4','Race Buyer','22222',null,'88888888-8888-4888-8888-888888888882');");Must $pb 'different payment B';$p4b=Uuid $pb
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o4','$p4a','race-event-4a','Payment A');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_confirm_payment('$o4','$p4b','race-event-4b','Payment B');"));Inspect-Race $r;Assert-One-Winner $r 'different-payment confirm'
  Count "select count(*) from public.payments where order_id='$o4' and status='paid'" 1 'different-payment paid count';Count "select count(*) from public.order_fulfillment_events where order_id='$o4'" 1 'different-payment event count';Count "select count(*) from public.audit_logs where action='payment.confirmed' and target_id in('$p4a','$p4b')" 1 'different-payment audit count';'TEST 5 [PASS] different payments: exactly one paid, one event, one audit'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'89999999-9999-4999-8999-999999999999');");Must $new 'bank-cash order';$o5=Uuid $new
  $bank=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o5','Race Buyer','33333',null,'8aaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');");Must $bank 'bank-cash bank payment';$p5=Uuid $bank
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o5','$p5','race-event-5-bank','Bank wins');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_confirm_cash_payment('$o5','8bbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Cash wins');"));Inspect-Race $r;Assert-One-Winner $r 'bank-vs-cash'
  Count "select count(*) from public.payments where order_id='$o5' and status='paid'" 1 'bank-cash paid count';Count "select count(*) from public.order_fulfillment_events where order_id='$o5'" 1 'bank-cash event count';Count "select count(*) from public.audit_logs where action='payment.confirmed' and target_id in(select id from public.payments where order_id='$o5')" 1 'bank-cash audit count';'TEST 6 [PASS] bank vs cash: exactly one paid, one event, one financial audit'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'8ccccccc-cccc-4ccc-8ccc-cccccccccccc');");Must $new 'confirm-reject order';$o6=Uuid $new
  $payment=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o6','Race Buyer','44444',null,'8ddddddd-dddd-4ddd-8ddd-dddddddddddd');");Must $payment 'confirm-reject payment';$p6=Uuid $payment
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o6','$p6','race-event-6','Confirm race');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_reject_payment_submission('$p6','Reject race');"));Inspect-Race $r;Assert-One-Winner $r 'confirm-vs-reject'
  $state=(Invoke-Db "select o.status::text||'|'||o.payment_status::text||'|'||p.status::text||'|'||s.status::text||'|'||(select count(*) from public.order_fulfillment_events where order_id=o.id) from public.orders o join public.payments p on p.order_id=o.id join public.payment_submissions s on s.payment_id=p.id where o.id='$o6'").Output
  if(-not(@('paid|paid|paid|approved|1','awaiting_payment|failed|failed|rejected|0') -contains $state)){$stats.PartialState++;throw "partial confirm/reject state: $state"};Count "select count(*) from public.audit_logs where target_id='$p6' and action in('payment.confirmed','payment_submission.rejected')" 1 'confirm-reject audit count';'TEST 7 [PASS] confirm vs reject: one consistent terminal payment outcome'

  if($stats.Deadlock-ne 0 -or $stats.UniqueViolation-ne 0 -or $stats.IntegrityRejection-ne 0 -or $stats.PartialState-ne 0){throw "Unexpected concurrency errors: 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23xxx=$($stats.IntegrityRejection) partial=$($stats.PartialState)"}
  "SUMMARY 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23xxx=$($stats.IntegrityRejection) domain=$($stats.DomainRejection) partial=$($stats.PartialState)"
}finally{Must (Invoke-Db $cleanup) 'cleanup'}
