# LOCAL-only true multi-session validation for P1-5C.
[CmdletBinding()]param([ValidatePattern('^supabase_db_[A-Za-z0-9_-]+$')][string]$ContainerName)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$docker=(Get-Command docker -ErrorAction Stop).Source
if(-not $ContainerName){$names=@(& $docker --host 'npipe:////./pipe/docker_engine' ps --format '{{.Names}}'|Where-Object{$_ -like 'supabase_db_*'});if($names.Count-ne 1){throw "Expected one local Supabase DB container; found $($names.Count)."};$ContainerName=$names[0]}
function Invoke-Db([string]$Sql){$out=& $docker --host 'npipe:////./pipe/docker_engine' exec $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At -c $Sql 2>&1|Out-String;[pscustomobject]@{ExitCode=$LASTEXITCODE;Output=$out.Trim()}}
function Start-Db([string]$Sql){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$docker;$i.Arguments="--host npipe:////./pipe/docker_engine exec -i $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At";$i.UseShellExecute=$false;$i.RedirectStandardInput=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$i;[void]$p.Start();$p.StandardInput.Write($Sql);$p.StandardInput.Close();$p}
function Wait-Db($Process){$o=$Process.StandardOutput.ReadToEndAsync();$e=$Process.StandardError.ReadToEndAsync();if(-not $Process.WaitForExit(30000)){$Process.Kill();throw 'DB session timeout'};[pscustomobject]@{ExitCode=$Process.ExitCode;Output=(($o.Result+[Environment]::NewLine+$e.Result).Trim())}}
function Race([string[]]$Sql){$ps=@($Sql|ForEach-Object{Start-Db $_});@($ps|ForEach-Object{Wait-Db $_})}
function Auth([string]$User,[string]$Body){"begin;set local role authenticated;select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','$User',true);set local statement_timeout='15s';$Body commit;"}
function Must($Result,[string]$Name){if($Result.ExitCode-ne 0){throw "$Name failed: $($Result.Output)"}}
function Db-Uuid([string]$Sql){$r=Invoke-Db $Sql;Must $r 'UUID query';$m=[regex]::Matches($r.Output,'(?i)[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}');if($m.Count-eq 0){throw "No UUID found: $($r.Output)"};$m[$m.Count-1].Value}
function Count([string]$Sql,[int]$Expected,[string]$Name){$r=Invoke-Db $Sql;Must $r $Name;$n=[int](($r.Output-split'[\r\n]+')[-1]);if($n-ne$Expected){$script:stats.Partial++;throw "$Name expected $Expected got $n"}}
function Inspect($Results){foreach($r in $Results){if($r.Output-match'ERROR:\s+40P01'){$script:stats.Deadlock++};if($r.Output-match'ERROR:\s+23505'){$script:stats.UniqueViolation++};if($r.Output-match'ERROR:\s+23P01'){$script:stats.ExclusionViolation++};if($r.Output-match'ERROR:\s+P0001'){$script:stats.Domain++};if($r.Output-match'ERROR:\s+23[0-9A-Z]{3}'-and$r.Output-notmatch'ERROR:\s+(23505|23P01)'){$script:stats.UnexpectedIntegrity++}}}
function One-Winner($Results,[string]$Name){$wins=@($Results|Where-Object{$_.ExitCode-eq 0}).Count;$unexpected=@($Results|Where-Object{$_.ExitCode-ne 0-and$_.Output-notmatch'ERROR:\s+P0001'}).Count;if($wins-ne 1-or$unexpected-ne 0){$script:stats.Partial++;throw "$Name expected one success and one domain rejection: $($Results.Output-join' | ')"}}
$stats=[ordered]@{Deadlock=0;UniqueViolation=0;ExclusionViolation=0;UnexpectedIntegrity=0;Domain=0;Partial=0}
$student='7a000000-0000-0000-0000-000000000001';$teacher='7a000000-0000-0000-0000-000000000002';$relationship='7a000000-0000-0000-0000-000000000010';$entitlement='7a000000-0000-0000-0000-000000000020'
$rights=@('7a000000-0000-0000-0001-000000000001','7a000000-0000-0000-0001-000000000002','7a000000-0000-0000-0001-000000000003','7a000000-0000-0000-0001-000000000004')
$cleanup="begin;set local session_replication_role='replica';delete from public.lesson_records where lesson_id in(select id from public.lessons where student_user_id='$student');delete from public.makeup_right_operations where makeup_right_id in('$($rights[0])','$($rights[1])','$($rights[2])','$($rights[3])');delete from public.audit_logs where actor_user_id in('$student','$teacher');delete from public.bookings where student_user_id='$student';delete from public.lesson_credit_ledger where beneficiary_user_id='$student';delete from public.lesson_credit_reservations where beneficiary_user_id='$student';delete from public.makeup_rights where student_user_id='$student';delete from public.lessons where student_user_id='$student';delete from public.teacher_availability_rules where teacher_user_id='$teacher';delete from public.teacher_scheduling_settings where teacher_user_id='$teacher';delete from public.entitlements where beneficiary_user_id='$student';delete from public.student_teacher_relationships where id='$relationship';delete from public.teacher_public_profiles where public_slug='makeup-booking-race-teacher';delete from public.teacher_profiles where user_id='$teacher';delete from public.public_profiles where user_id in('$student','$teacher');delete from public.user_roles where user_id in('$student','$teacher');delete from public.profiles where user_id in('$student','$teacher');delete from auth.users where id in('$student','$teacher');commit;"
$setup=$cleanup+"insert into auth.users(id,email)values('$student','makeup-booking-race-student@example.invalid'),('$teacher','makeup-booking-race-teacher@example.invalid');insert into public.user_roles(user_id,role)values('$teacher','teacher');insert into public.teacher_profiles(user_id,public_slug,bio,teaching_status,is_public,teaching_modes,trial_price_twd,default_meeting_provider,default_meeting_url)values('$teacher','makeup-booking-race-teacher','Race fixture','active',true,array['online']::public.teaching_mode[],500,'manual_google_meet','https://meet.google.com/abc-defg-hij');insert into public.student_teacher_relationships(id,student_user_id,teacher_user_id,relationship_status,preferred_mode)values('$relationship','$student','$teacher','active','online');insert into public.teacher_scheduling_settings(teacher_user_id,timezone,minimum_booking_notice_minutes,booking_horizon_days,slot_interval_minutes)values('$teacher','UTC',0,90,10);insert into public.teacher_availability_rules(teacher_user_id,weekday,local_start_time,local_end_time,timezone,effective_from,effective_until,created_by)select '$teacher',extract(dow from current_date+14)::smallint,'08:00','23:30','UTC',current_date,current_date+90,'$teacher';insert into public.entitlements(id,beneficiary_user_id,teacher_scope_user_id,entitlement_type,status,starts_at,expires_at,product_name_snapshot,booking_mode_eligibility,lesson_duration_minutes)values('$entitlement','$student','$teacher','lesson_package','active',now()-interval '1 day',now()+interval '6 months','Makeup same-slot race','flexible',50);insert into public.lesson_credit_ledger(entitlement_id,beneficiary_user_id,entry_type,available_delta,operation_key,reason_code)values('$entitlement','$student','allocation',1,'makeup-booking-race-allocation','fixture');insert into public.lessons(id,student_user_id,teacher_user_id,relationship_id,lesson_type,delivery_mode,starts_at,ends_at,duration_minutes,timezone_anchor,status,meeting_provider,meeting_url)select ('7a000000-0000-0000-0002-'||lpad(n::text,12,'0'))::uuid,'$student','$teacher','$relationship','flexible','online',now()-(n+2)*interval '1 day',now()-(n+2)*interval '1 day'+interval '50 minutes',50,'UTC','completed','manual_google_meet','https://meet.google.com/abc-defg-hij' from generate_series(1,4)n;insert into public.makeup_rights(id,student_user_id,origin_lesson_id,origin_teacher_user_id,current_teacher_user_id,source,source_operation_key,status,valid_until,reason,created_by)select ('7a000000-0000-0000-0001-'||lpad(n::text,12,'0'))::uuid,'$student',('7a000000-0000-0000-0002-'||lpad(n::text,12,'0'))::uuid,'$teacher','$teacher','teacher_cancellation','makeup-booking-race-right-'||lpad(n::text,4,'0'),'available',now()+interval '30 days','Race fixture','$teacher' from generate_series(1,4)n;"
function Slot([int]$Hour){"((current_date+14)::timestamp+interval '$Hour hours') at time zone 'UTC'"}
function Create-Makeup([string]$Right,[int]$Hour,[string]$Key){"select public.create_makeup_lesson_booking('$Right','$student','$teacher','$relationship',$(Slot $Hour),'UTC','$Key','Concurrent Makeup booking');"}
try{
  Must (Invoke-Db $setup) 'setup'
  $race=Race @((Auth $student "select pg_sleep(.2);$(Create-Makeup $rights[0] 10 'makeup-race-same-right-a');"),(Auth $student "select pg_sleep(.2);$(Create-Makeup $rights[0] 11 'makeup-race-same-right-b');"));Inspect $race;One-Winner $race 'A same Right different slots';Count "select count(*) from public.bookings where makeup_right_id='$($rights[0])' and status in('confirmed','rescheduled')" 1 'A active booking';Count "select count(*) from public.makeup_right_operations where makeup_right_id='$($rights[0])' and operation_type='reserve'" 1 'A reserve operation';'A [PASS] Same Makeup Right concurrent booking has exactly one winner'
  $bookingB=Db-Uuid (Auth $student (Create-Makeup $rights[1] 12 'makeup-race-complete-cancel'));$lessonB=Db-Uuid "select lesson_id from public.bookings where id='$bookingB'";Must (Invoke-Db "update public.lessons set starts_at=now()-interval '1 hour',ends_at=now()-interval '10 minutes' where id='$lessonB';update public.bookings set starts_at=now()-interval '1 hour',ends_at=now()-interval '10 minutes' where id='$bookingB';") 'B time fixture'
  $race=Race @((Auth $teacher "select pg_sleep(.2);select public.complete_lesson_booking('$bookingB','Visible','Private','Summary','Goal','Homework');"),(Auth $student "select pg_sleep(.2);select public.cancel_lesson_booking('$bookingB','released','Concurrent timely cancellation');"));Inspect $race;One-Winner $race 'B completion vs cancellation';Count "select count(*) from public.bookings b join public.lessons l on l.id=b.lesson_id join public.makeup_rights r on r.id=b.makeup_right_id where b.id='$bookingB' and ((b.status='completed' and l.status='completed' and r.status='used') or (b.status='cancelled' and l.status='student_cancelled' and r.status='available'))" 1 'B consistent state';Count "select count(*) from public.makeup_right_operations where makeup_right_id='$($rights[1])' and operation_type in('consume','restore')" 1 'B terminal movement';'B [PASS] Completion versus timely cancellation has one authoritative outcome'
  $bookingC=Db-Uuid (Auth $student (Create-Makeup $rights[2] 13 'makeup-race-teacher-cancel'));$lessonC=Db-Uuid "select lesson_id from public.bookings where id='$bookingC'";Must (Invoke-Db "update public.lessons set starts_at=now()-interval '1 hour',ends_at=now()-interval '10 minutes' where id='$lessonC';update public.bookings set starts_at=now()-interval '1 hour',ends_at=now()-interval '10 minutes' where id='$bookingC';") 'C time fixture'
  $race=Race @((Auth $teacher "select pg_sleep(.2);select public.complete_lesson_booking('$bookingC','Visible','Private','Summary','Goal','Homework');"),(Auth $teacher "select pg_sleep(.2);select public.cancel_lesson_booking('$bookingC','released','Concurrent Teacher cancellation','teacher_caused');"));Inspect $race;One-Winner $race 'C Teacher cancellation vs completion';Count "select count(*) from public.bookings b join public.lessons l on l.id=b.lesson_id join public.makeup_rights r on r.id=b.makeup_right_id where b.id='$bookingC' and ((b.status='completed' and l.status='completed' and r.status='used') or (b.status='cancelled' and l.status='teacher_cancelled' and r.status='available'))" 1 'C consistent state';Count "select count(*) from public.makeup_rights where id='$($rights[2])'" 1 'C one Right';'C [PASS] Teacher cancellation versus completion preserves one value outcome'
  $race=Race @((Auth $student "select pg_sleep(.2);$(Create-Makeup $rights[3] 14 'makeup-race-value-source-m');"),(Auth $student "select pg_sleep(.2);select public.create_lesson_booking('$student','$teacher','$relationship','$entitlement',$(Slot 14),'UTC','makeup-race-value-source-o','Ordinary same-slot race');"));Inspect $race;One-Winner $race 'D Makeup vs ordinary same slot';Count "select count(*) from public.bookings where starts_at=$(Slot 14) and status in('confirmed','rescheduled')" 1 'D slot owner';Count "select count(*) from public.bookings b where b.starts_at=$(Slot 14) and ((b.source='makeup' and b.makeup_right_id='$($rights[3])' and b.credit_reservation_id is null) or (b.source='flexible' and b.makeup_right_id is null and b.credit_reservation_id is not null))" 1 'D value source';'D [PASS] Makeup versus ordinary same-slot booking has exactly one winner'
  if($stats.Deadlock-ne 0-or$stats.UniqueViolation-ne 0-or$stats.ExclusionViolation-ne 0-or$stats.UnexpectedIntegrity-ne 0-or$stats.Partial-ne 0){throw "Unexpected result: 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23P01=$($stats.ExclusionViolation) unexpected23xxx=$($stats.UnexpectedIntegrity) partial=$($stats.Partial)"}
  "SUMMARY 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) 23P01=$($stats.ExclusionViolation) unexpected23xxx=$($stats.UnexpectedIntegrity) domain=$($stats.Domain) partial=$($stats.Partial)"
}finally{Must (Invoke-Db $cleanup) 'cleanup'}
