[CmdletBinding()]param([string]$ContainerName)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$docker=(Get-Command docker -ErrorAction Stop).Source
if(-not $ContainerName){$names=@(& $docker ps --format '{{.Names}}'|Where-Object{$_ -like 'supabase_db_*'});if($names.Count-ne 1){throw "Expected one local Supabase DB container; found $($names.Count)."};$ContainerName=$names[0]}
function Invoke-Db([string]$Sql){$out=& $docker exec $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At -c $Sql 2>&1|Out-String;[pscustomobject]@{ExitCode=$LASTEXITCODE;Output=$out.Trim()}}
function Start-Db([string]$Sql){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$docker;$i.Arguments="exec -i $ContainerName psql -X -U postgres -d postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -At";$i.UseShellExecute=$false;$i.RedirectStandardInput=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$i;[void]$p.Start();$p.StandardInput.Write($Sql);$p.StandardInput.Close();$p}
function Wait-Db($Process){$o=$Process.StandardOutput.ReadToEndAsync();$e=$Process.StandardError.ReadToEndAsync();if(-not $Process.WaitForExit(30000)){$Process.Kill($true);throw 'DB session timeout'};[pscustomobject]@{ExitCode=$Process.ExitCode;Output=(($o.Result+"`n"+$e.Result).Trim())}}
function Race([string[]]$Sql){$ps=@($Sql|ForEach-Object{Start-Db $_});@($ps|ForEach-Object{Wait-Db $_})}
function Auth([string]$User,[string]$Body){"begin;set local role authenticated;select set_config('request.jwt.claim.sub','$User',true);set local statement_timeout='15s';$Body commit;"}
function Must($Result,[string]$Name){if($Result.ExitCode-ne 0){throw "$Name failed: $($Result.Output)"}}
function Uuid($Result){$matches=[regex]::Matches($Result.Output,'(?i)[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}');if($matches.Count-eq 0){throw "No UUID in DB session output: $($Result.Output)"};$matches[$matches.Count-1].Value}
function Count([string]$Sql,[int]$Expected,[string]$Name){$r=Invoke-Db $Sql;Must $r $Name;$n=[int](($r.Output-split"`r?`n")[-1]);if($n-ne$Expected){throw "$Name expected $Expected got $n"}}
$stats=[ordered]@{Deadlock=0;UniqueViolation=0;PartialState=0}
function Inspect-Race($Results){foreach($result in $Results){if($result.Output -match '40P01'){$stats.Deadlock++};if($result.Output -match '23505'){$stats.UniqueViolation++}}}
$buyer='71000000-0000-0000-0000-000000000001';$admin1='71000000-0000-0000-0000-000000000002';$admin2='71000000-0000-0000-0000-000000000003'
$cleanup="delete from public.audit_logs where actor_user_id in ('$admin1','$admin2');delete from public.order_fulfillment_events where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.payment_submissions where buyer_user_id='$buyer';delete from public.refunds where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.payments where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.order_items where order_id in(select id from public.orders where buyer_user_id='$buyer');delete from public.orders where buyer_user_id='$buyer';delete from public.product_public_catalog where public_slug='epic4-race-product';delete from public.products where public_slug='epic4-race-product';delete from public.user_roles where user_id in('$buyer','$admin1','$admin2');delete from public.profiles where user_id in('$buyer','$admin1','$admin2');delete from auth.users where id in('$buyer','$admin1','$admin2');"
$setup="$cleanup insert into auth.users(id,email) values('$buyer','epic4-race-buyer@example.invalid'),('$admin1','epic4-race-admin1@example.invalid'),('$admin2','epic4-race-admin2@example.invalid');insert into public.user_roles(user_id,role) values('$admin1','admin'),('$admin2','admin');insert into public.products(product_type,status,public_slug,name,currency,base_price_amount,owner_type,is_public,is_purchasable,published_at) values('lesson_package','active','epic4-race-product','Race Product','TWD',3200,'platform',true,true,now());"
try{
  Must (Invoke-Db $setup) 'setup'
  $checkout=Auth $buyer "select pg_sleep(.3);select public.create_checkout_order('epic4-race-product',1,'81111111-1111-4111-8111-111111111111');"
  $r=Race @($checkout,$checkout);Inspect-Race $r;$r|ForEach-Object{Must $_ 'same-key checkout'};$ids=@($r|ForEach-Object{Uuid $_});if($ids[0]-ne$ids[1]){throw 'checkout returned different IDs'};Count "select count(*) from public.orders where buyer_user_id='$buyer' and idempotency_key='81111111-1111-4111-8111-111111111111'" 1 'checkout count';'TEST 1 [PASS] same-key checkout: same order, no 23505'

  $order=$ids[0];$submit=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$order','Race Buyer','12345',null,'82222222-2222-4222-8222-222222222222');");Must $submit 'payment setup';$payment=Uuid $submit
  $confirm=Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$order','$payment','race-event-1','Concurrency validation');"
  $confirm2=Auth $admin2 "select pg_sleep(.3);select public.admin_confirm_payment('$order','$payment','race-event-1','Concurrency validation');"
  $r=Race @($confirm,$confirm2);Inspect-Race $r;$r|ForEach-Object{Must $_ 'double confirm'};Count "select count(*) from public.order_fulfillment_events where order_id='$order'" 1 'double-confirm event';Count "select count(*) from public.audit_logs where target_id='$payment'" 1 'double-confirm audit';'TEST 2 [PASS] double confirmation: one paid effect and one outbox event'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'83333333-3333-4333-8333-333333333333');");Must $new 'cancel race order';$o2=Uuid $new;$pay=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o2','Race Buyer','12345',null,'84444444-4444-4444-8444-444444444444');");Must $pay 'cancel race payment';$p2=Uuid $pay
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o2','$p2','race-event-2','Race confirm');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_cancel_order('$o2','Race cancel');"));Inspect-Race $r;if(@($r|Where-Object{$_.ExitCode -eq 0}).Count -ne 1){throw "cancel/payment expected one winner: $($r.Output-join' | ')"};$state=(Invoke-Db "select status::text||'|'||payment_status::text||'|'||(select count(*) from public.order_fulfillment_events where order_id='$o2') from public.orders where id='$o2'").Output;if(-not(@('paid|paid|1','cancelled|unpaid|0') -contains $state)){$stats.PartialState++;throw "partial cancel/payment state: $state"};'TEST 3 [PASS] cancel/payment race: consistent winner state'

  $new=Invoke-Db (Auth $buyer "select public.create_checkout_order('epic4-race-product',1,'85555555-5555-4555-8555-555555555555');");Must $new 'expiry race order';$o3=Uuid $new;$pay=Invoke-Db (Auth $buyer "select public.submit_bank_transfer('$o3','Race Buyer','12345',null,'86666666-6666-4666-8666-666666666666');");Must $pay 'expiry race payment';$p3=Uuid $pay;Must (Invoke-Db "update public.orders set expires_at=now()-interval '1 second' where id='$o3'") 'backdate expiry'
  $r=Race @((Auth $admin1 "select pg_sleep(.3);select public.admin_confirm_payment('$o3','$p3','race-event-3','Race confirm');"),(Auth $admin2 "select pg_sleep(.3);select public.admin_expire_order('$o3','Race expiry');"));Inspect-Race $r;if(@($r|Where-Object{$_.ExitCode -eq 0}).Count -ne 1){throw "expiry/payment expected one winner: $($r.Output-join' | ')"};$state=(Invoke-Db "select status::text||'|'||payment_status::text||'|'||(select count(*) from public.order_fulfillment_events where order_id='$o3') from public.orders where id='$o3'").Output;if(-not(@('paid|paid|1','expired|unpaid|0') -contains $state)){$stats.PartialState++;throw "partial expiry/payment state: $state"};'TEST 4 [PASS] expiry/payment race: consistent winner state'
  if($stats.Deadlock -ne 0 -or $stats.UniqueViolation -ne 0 -or $stats.PartialState -ne 0){throw "Unexpected concurrency errors: 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) partial=$($stats.PartialState)"}
  "SUMMARY 40P01=$($stats.Deadlock) 23505=$($stats.UniqueViolation) partial=$($stats.PartialState)"
}finally{Must (Invoke-Db $cleanup) 'cleanup'}
