"use client";
import Link from "next/link";
import { useState } from "react";
import { learningPreview } from "@/lib/preview/learning";
import { Progress, ResourceRow } from "./ui";
type Lesson = typeof learningPreview.lessons[number];
function LessonNavigation({ current }: { current: string }) {
 return <nav aria-label="課節導覽" className="lesson-navigation"><Link href="/student/map" className="text-link">← 回到學習地圖</Link><p className="eyebrow">LEVEL 01</p><h2>節奏與第一首歌</h2><Progress value={38} label="練習進度（示範）"/>{learningPreview.lessons.map((lesson,i)=>lesson.state==="locked"?<div className="lesson-nav-item locked" key={lesson.id}><span>◇</span><div>{lesson.title}<small>尚未解鎖</small></div></div>:<Link aria-current={lesson.id===current?"page":undefined} className="lesson-nav-item" key={lesson.id} href={"/student/learn/"+lesson.id}><span>{lesson.state==="completed"?"✓":"0"+(i+1)}</span><div>{lesson.title}<small>{lesson.minutes} 分鐘</small></div></Link>)}</nav>;
}
export function LessonWorkspace({ lesson }: { lesson: Lesson }) {
 const [practiced,setPracticed]=useState(false);
 const index=learningPreview.lessons.findIndex(x=>x.id===lesson.id);
 const previous=learningPreview.lessons[index-1],next=learningPreview.lessons[index+1];
 return <main className="workspace"><aside className="desktop-lesson-nav"><LessonNavigation current={lesson.id}/></aside><article className="lesson-content"><div className="video-placeholder"><div className="video-rings"/><span className="video-label">THE ONE / LEARNING SESSION</span><span className="play-symbol" aria-hidden="true">▷</span><h2>先感受節奏，再拿起吉他。</h2><p>教學影片準備中 · 此區展示播放器位置，無實際影片</p><div className="video-controls"><span>00:00</span><div/><span>— : —</span></div></div><header className="lesson-title"><p className="eyebrow">MODULE 01 · 約 {lesson.minutes} 分鐘</p><h1>{lesson.title}</h1></header><section className="lesson-goal"><p className="eyebrow">這一課，我想做到</p><h2>{lesson.objective}</h2></section><div className="mobile-resources"><Resources/></div><div className="lesson-pager">{previous?<Link className="cta cta-secondary" href={"/student/learn/"+previous.id}>← 上一課</Link>:<Link className="cta cta-secondary" href="/student/map">← 學習地圖</Link>}{next&&next.state!=="locked"?<Link className="cta" href={"/student/learn/"+next.id}>下一課 →</Link>:<span className="soft-pill">下一課尚未解鎖</span>}</div><details className="mobile-lesson-nav"><summary>課節目錄 · 查看學習路線</summary><LessonNavigation current={lesson.id}/></details><section className="key-points"><h2>把這三件事，帶進練習裡。</h2><ol><li><span>01</span><div><h3>先聽，再動手</h3><p>跟著音樂數拍，找到穩定的脈動，不急著加快。</p></div></li><li><span>02</span><div><h3>讓右手保持移動</h3><p>即使沒有刷到弦，也讓擺動連續，留意身體是否放鬆。</p></div></li><li><span>03</span><div><h3>把練習放回音樂</h3><p>選兩個熟悉的和弦，試著連續彈奏，不因轉換停下來。</p></div></li></ol></section><section id="practice" className="practice-panel"><p className="eyebrow">YOUR TURN / 5 MIN</p><h2>現在，換你試試看。</h2><p>放慢速度，連續完成四個小節。注意節拍，不追求完美。</p><button className="cta cta-secondary" onClick={()=>setPracticed(!practiced)} aria-pressed={practiced}>{practiced?"撤回本次練習標記":"我已經試著練習"}</button><p role="status">{practiced?"已在本頁暫記；重新載入即清除，不代表通過能力驗證。":"這是本頁暫存的練習標記，不儲存或授予正式進度。"}</p></section></article><aside className="desktop-resources"><Resources/><div className="teacher-tip"><p className="eyebrow">給你的小提醒</p><h3>穩定，比速度重要。</h3><p>如果今天只有五分鐘，把一個動作練得更舒服，也是一種進步。</p><small>示範學習建議</small></div></aside></main>;
}
function Resources() {return <section className="workspace-resources"><p className="eyebrow">YOUR LEARNING KIT</p><h2>這一課的學習資源</h2><ResourceRow kind="PDF" title="節奏練習圖解" detail="閱讀與練習筆記"/><ResourceRow kind="♫" title="慢速示範音檔" detail="先聽見穩定的節拍"/><ResourceRow kind="▶" title="練習伴奏" detail="把動作放回音樂"/><small>資源位置展示，尚無下載檔案。</small></section>;}
