"use client";
import { useState } from "react";
import Link from "next/link";
import { learningPreview } from "@/lib/preview/learning";
import { Progress, PrimaryCTA } from "./ui";
export function LearningStageExplorer() {
 const [selected,setSelected]=useState(0);
 return <div className="map-grid"><div className="map-landscape"><div className="mountain mountain-back"/><div className="mountain mountain-front"/><ol className="stage-path" aria-label="學習階段">{learningPreview.stages.map((title,i)=><li key={title} className={i===selected?"selected":""}><button onClick={()=>setSelected(i)} aria-pressed={i===selected}><span className="stage-number">{i===0?"◉":String(i+1).padStart(2,"0")}</span><span><small>LEVEL 0{i+1}{i===0?" · 目前階段":" · 尚未解鎖"}</small><strong>{title}</strong></span><span aria-hidden="true">↗</span></button></li>)}</ol><span className="landscape-caption">EVERY SMALL STEP COUNTS.</span></div><section className="stage-detail" aria-live="polite"><p className="eyebrow">LEVEL 0{selected+1} / {selected===0?"你正在這裡":"下一段旅程"}</p><h2>{learningPreview.stages[selected]}</h2><p className="body-copy">{selected===0?"從聽見節拍，到接起和弦。讓一小段音樂，完整地從你手裡流出來。":"先把眼前的一步走穩。這一階段的課節尚未開放，現在可以預覽成果方向。"}</p><Progress value={selected===0?38:0} label="階段練習進度（示範）"/>{selected===0?<><p className="eyebrow module-label">MODULE 01 · 節奏與第一首歌</p><div className="node-list">{learningPreview.lessons.map((lesson,i)=><div key={lesson.id} className={"node-row "+lesson.state}><span>{lesson.state==="completed"?"✓":lesson.state==="locked"?"◇":String(i+1).padStart(2,"0")}</span><div><strong>{lesson.title}</strong><small>{lesson.minutes} 分鐘 · {{completed:"已練習",current:"目前課節",upcoming:"接下來",locked:"尚未解鎖"}[lesson.state]}</small></div>{lesson.state!=="locked"&&<Link href={"/student/learn/"+lesson.id} aria-label={"開啟："+lesson.title}>↗</Link>}</div>)}</div><PrimaryCTA href="/student/learn/pulse">繼續目前課節</PrimaryCTA></>:<div className="locked-note"><span>◇</span><h3>先專注在現在的練習。</h3><p>這裡不會自動開通存取權，也不代表已取得正式課程資格。</p><button className="cta cta-secondary" onClick={()=>setSelected(0)}>回到目前階段 →</button></div>}<p className="muted map-disclaimer">課節、解鎖與進度僅為 UX 示範；不是正式能力驗證。</p></section></div>;
}
